<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$action = Mage::app()->getFrontController()->getAction();
$path = $action->getFullActionName('');
$siteKey =  Mage::helper('tejar_captcha')->getConfigNode('public_key');
$captchaModel = Mage::helper('captcha')->getCaptcha("newsletter_captcha");
?>
<?php if(Mage::helper('tejar_captcha')->getConfigNode('recaptcha_enable') && $captchaModel->isRequired()): ?>
<?php if(!Mage::getSingleton('core/session')->getCaptchaScript()): ?>
	<script src="https://www.google.com/recaptcha/api.js?render=<?php echo $siteKey; ?>"></script>
<?php endif; ?>
<?php Mage::getSingleton('core/session')->unsCaptchaScript(); ?>
<?php endif; ?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" class="subscribe" novalidate>
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<div class="newsletter newsletter_box">
<label for="newsletter_email" id="newsletterEmail" class="no-display">Email</label>
<input type="email" name="email" aria-labelledby="newsletterEmail" id="newsletter_email" placeholder="Enter your email address" class="input-text required-entry validate-email">
<?php if(Mage::helper('tejar_captcha')->getConfigNode('recaptcha_enable') && $captchaModel->isRequired()): ?>
	<p style="color: #fff;">This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.</p>
<input type="hidden" id="g-recaptcha-token-sec-id" name="g-recaptcha-token" value="" />
<script type="text/javascript">
	grecaptcha.ready(function() {
		grecaptcha.execute('<?php echo $siteKey; ?>', {action: '<?php echo $path . "page"; ?>'})
		.then(function(token) {
			document.getElementById('g-recaptcha-token-sec-id').value = token;
		});
	});
</script>
<?php endif; ?>
<button type="submit" class="def_icon_btn" aria-label="Submit" aria-hidden="true"></button>
</div>
<?php echo $this->getChildHtml('form.additional.info'); ?>
</form>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(){
	var newsletterSubscriberFormDetail = new VarienForm("newsletter-validate-detail");
});
</script>
