<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>

<?php 
$_menu = $this->getHtml('level-top');
?>
	

<?php if ($_menu): ?>
	<?php echo $_menu ?>
<?php endif ?>
						