<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license/regular
 */
/**
 * Scripts added before the body closing tag
 */
?>
<?php echo $this->getCssJsHtml(); ?>
<?php $controllerName = $this->getRequest()->getControllerName(); ?>
<?php $fullActionName = Mage::app()->getFrontController()->getAction()->getFullActionName(); ?>
<?php $curAjaxPageURL =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>

<?php $isHomePage = $this->getUrl('') == $this->getUrl('*/*/*', array('_current'=>true, '_use_rewrite'=>true)); ?>
<?php $isSliderAjax = Mage::getStoreConfig('filterproducts/general_config/ajaxslider' , Mage::app()->getStore()); ?>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
(function() {
	var Enumerable1 = Array.prototype;
	function findAll(iterator, context) {
		var results = [];
		// 3SD CODE FOR RECAPTCHA ERROR
		if(NodeList.prototype.isPrototypeOf(this)) return results;
		this.each(function(value, index) {
		  if (iterator.call(context, value, index))
			results.push(value);
		});
		return results;
	}
	Object.extend(Enumerable1, Enumerable);
	Object.extend(Enumerable1, {
		findAll:    findAll,
		select:     findAll,
		filter:     findAll,
	});
})();
});
</script>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
	var i = 0;
	<?php if($isHomePage && $isSliderAjax): ?>
		// Home Product Slider
		var sliderUpdate = function(block, display, productCount){
			new Ajax.Request("/filterproducts/index/productsSlider/form_key/<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>/",{
				method:'get',
				evalScripts: true,
				asynchronous: true,
				parameters:{'block_name':block, 'display_type':display, 'products_count':productCount},
				onSuccess: function(transport)    {
					if(200 == transport.status) {
						var json = transport.responseText.evalJSON(true);
						if(json.trim() !== ""){
							$('featured_products_'+block).update(json);
						} else {
							$('featured_products_'+block).up('.owl-section-content').hide();
						}
						var slick = $j("#featured_products_"+block+"  .filter-products .products-slider");
						slick.on('init breakpoint', function(event, slick, currentSlide, nextSlide){
							$j("[id*=full-name-]")&&$j("[id*=full-name-]").each(function(){$j(this).trunk8({lines:2})});
							425>=document.documentElement.clientWidth?$j(".owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:2,moreText:"+ ([COUNT])"}):$j(".owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:3,moreText:"+ ([COUNT])"});
						});
						slick.slick({lazyLoad:"ondemand",infinite: false,prevArrow:'<button class="slick-prev" aria-label="Previous" type="button"><span aria-label="Previous">\u2039</span></button>',nextArrow:'<button class="slick-next" aria-label="Next" type="button"><span aria-label="Next">\u203a</span></button>',speed:1E3,slidesToShow:2,slidesToScroll:2,speed: 300,
						responsive:[{breakpoint:10240.9,settings:{slidesToShow:10,slidesToScroll:10}},{breakpoint:1920.9,settings:{slidesToShow:9,slidesToScroll:9}},{breakpoint:1680.9,settings:{slidesToShow:8,slidesToScroll:8}},{breakpoint:1440.9,settings:{slidesToShow:7,slidesToScroll:7}},{breakpoint:1280.9,settings:{slidesToShow:6,slidesToScroll:6}},{breakpoint:1024.9,settings:{slidesToShow:5,slidesToScroll:5}},{breakpoint:992.9,settings:{slidesToShow:4,slidesToScroll:4}},{breakpoint:768.9,settings:{slidesToShow:3,slidesToScroll:3}},{breakpoint:480.9,settings:{
							slidesToShow:2,slidesToScroll:2
							}}]
						});
					}
				},
				onComplete: function(response) {if (200 == response.status){ i++; loop(i); } },
				onFailure: function(transport){ $j("#ajax-errors").show(); }
			});
		}

		var loop = function(i){ $$('[id*=featured_products_]').each(function(el , index){ if(index === i) sliderUpdate(el.dataset.block , el.dataset.display, el.dataset.productcount); }); }
		loop(i);

	<?php elseif($controllerName =='category' && $isSliderAjax): ?>
	 // Category Product Slider
		var Increment = [], Paging = [], Products = [];
		if($$('[id*=category_featured_products_]')) $$('[id*=category_featured_products_]').each(function(el , index){ Increment[el.dataset.block] = 1;  Paging[el.dataset.block] = 4;	});
		var url = document.location.href;
		var sliderCatUpdate = function(block, display, productCount){
			new Ajax.Request(url,{
				method:'get',
				evalScripts: true,
				asynchronous: true,
				parameters:{'slider':'true' , 'sp': '1' , 'productCount' : '12' , 'type' : block},
				onSuccess: function(transport)    {
					if(200 == transport.status && transport.readyState == 4) {
						var json = transport.responseText.evalJSON(true);
						$('category_featured_products_'+block).update(json[block]);
						Products[block] = $j("#category_featured_products_"+ block + " .filter-products .products-slider");
						Products[block].on('init breakpoint', function(event, slick, currentSlide, nextSlide){
							$j("[id*=full-name-]")&&$j("[id*=full-name-]").each(function(){$j(this).trunk8({lines:2})});
							425>=document.documentElement.clientWidth?$j(".owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:2,moreText:"+ ([COUNT])"}):$j(".owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:3,moreText:"+ ([COUNT])"});
						});

						Products[block].slick({lazyLoad:"ondemand", infinite: false, prevArrow:'<button class="slick-prev" aria-label="Previous" type="button"><span aria-label="Previous">\u2039</span></button>',nextArrow:'<button class="slick-next" aria-label="Next" type="button"><span aria-label="Next">\u203a</span></button>',speed:1E3,slidesToShow:2,slidesToScroll:2,speed: 300,
							responsive:[{breakpoint:10240.9,settings:{slidesToShow:10,slidesToScroll:5}},{breakpoint:1920.9,settings:{slidesToShow:9,slidesToScroll:5}},{breakpoint:1680.9,settings:{slidesToShow:8,slidesToScroll:5}},{breakpoint:1440.9,settings:{slidesToShow:7,slidesToScroll:5}},{breakpoint:1280.9,settings:{slidesToShow:6,slidesToScroll:3}},{breakpoint:1024.9,settings:{slidesToShow:5,slidesToScroll:5}},{breakpoint:992.9,settings:{slidesToShow:4,slidesToScroll:4}},{breakpoint:768.9,settings:{slidesToShow:3,slidesToScroll:3}},{breakpoint:480.9,settings:{slidesToShow:2,slidesToScroll:2}}]
						});

						Products[block].on('beforeChange', function(event, slick, currentSlide, nextSlide){
							if(nextSlide >= Paging[block]){
								Paging[block]+= 4;
								DynamicProduct(block);
								$j("#category_featured_products_"+ block +" [id*=full-name-]")&&$j("#category_featured_products_"+ block + " [id*=full-name-]").each(function(){$j(this).trunk8({lines:2})});
								425>=document.documentElement.clientWidth?$j("#category_featured_products_"+ block + " .owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:2,moreText:"+ ([COUNT])"}):$j("#category_featured_products_"+ block + " .owl-carousel .configurable-swatch-list-wrapper > ul").hideMaxListItemsSwatch({max:3,moreText:"+ ([COUNT])"});
							}
						});
					}
				},
				onComplete: function(response) { if (200 == response.status){ i++; loopCategories(i); } },
				onFailure: function(transport){ $j("#ajax-errors").show(); }
			});
		}


		DynamicProduct = function(block){
			var pages = $$('#category_featured_products_' + block + ' .filter-products .pager .pages ol li:not(.current)'), BreakException = {};
			try {pages.each(function(page , index){ if(pages.length !== 0){ page.classList.add("current"); DynamicProductAjax(block); } if (index === 0) throw BreakException; }); } catch(e){ if (e !== BreakException) throw e; }
		}

		DynamicProductAjax = function(block){
			Increment[block]++;
			new Ajax.Request(url,{
				method:'get',
				parameters:{'slider':'true' , 'sp': Increment[block], 'productCount' : '12' , 'type' : block},
				onSuccess: function(transport)    {
					if(200 == transport.status && transport.readyState == 4) {
						var dynamicProductArray = transport.responseText.evalJSON(true);
						var items = document.createElement('div');
						items.innerHTML = dynamicProductArray[block];
						var scripts = Array.prototype.slice.call(items.getElementsByTagName("script") , 0 );
						var items = Array.prototype.slice.call(items.querySelectorAll('.filter-products .products-slider .owl-item:not(.empty)'),0);
						var emptyProduct = Array.prototype.slice.call(document.querySelectorAll('#category_featured_products_' + block + ' .slick-track .owl-item.empty:not(.slick-cloned)'), 0);
						items.forEach(function(item , index) { emptyProduct[index].innerHTML = item.innerHTML; emptyProduct[index].classList.remove('empty'); });
						var dealSlider = document.querySelectorAll('#category_featured_products_'+block)[0];
						scripts.forEach(function(script , index) {
							try{scriptDiv = document.createElement('script'); scriptDiv.setAttribute('type', 'text/javascript'); scriptDiv.async = true; scriptDiv.innerHTML = script.innerHTML; dealSlider.appendChild(scriptDiv); }
							catch(e){ console.error(e); }
						});
					}
				},
				onFailure: function(transport){ $j("#ajax-errors").show(); }
			});
		}

		var loopCategories = function(){ $$('[id*=category_featured_products_]').each(function(el , index){ if(index === i) sliderCatUpdate(el.dataset.block , el.dataset.display, el.dataset.productcount); }); }
		loopCategories(i);

	<?php endif; ?>

});
</script>

<script type="text/javascript">
// 3SD Code Variable Declear
var lightboxInstance,
	lightboxMobileInstance;

// 3SD Code Script Run after Document Loaded
document.addEventListener("DOMContentLoaded", function() {



	// Init Auto Complete Seach
	searchAutoComplete('<?php echo $curAjaxPageURL;?>');

	// Init Foundation framework
	$j(document).foundation({
		topbar: {
			custom_back_text: true,
			back_text: '<?php echo $this->__("Back"); ?>'
		}
	});

	// Init Intenso Theme framework
	$j(document).intenso({
		productsGrid: {
			min_item_width: <?php echo Mage::getStoreConfig('intenso/catalog/catalog_min_product_width', Mage::app()->getStore()); ?>,
			number_items_on_mobile: <?php echo Mage::getStoreConfig('intenso/catalog/catalog_number_items_mobile', Mage::app()->getStore()); ?>
		},
		revealModalTimer: {
			duration: '<?php echo Mage::getStoreConfig('intenso/global_messages/time', Mage::app()->getStore()); ?>s'
		}
	});



	(function($){$("#currency").selectbox();})(jQuery);
	(function($){$(".select_theme").selectbox();})(jQuery);



	// Page Spacific

	<?php if($controllerName=='product' || $controllerName =='cart'
		|| ($controllerName =='category' && Mage::helper('itactica_quickview')->isEnabled())
		// || ($controllerName =='index' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($controllerName =='page' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($controllerName =='result' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($controllerName =='advanced' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($controllerName =='order' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($controllerName =='guest' && Mage::helper('itactica_quickview')->isEnabled())
		|| ($fullActionName == 'salesdeal_index_index')
		|| ($fullActionName == 'bestseller_index_index')
		|| ($fullActionName == 'mostviewed_index_index')
		|| ($fullActionName == 'newarrival_index_index')
		|| ($fullActionName == 'featuredproducts_index_index')
		|| $fullActionName == 'wishlist_index_configure'): ?>

	$j(function () {
		lightboxInstance = $j('.lightbox').imageLightbox({
			quit_on_doc_click: false
		});
		lightboxMobileInstance = $j('.lightbox-mobile').imageLightbox({
			quit_on_doc_click: false
		});
	});
	<?php endif; ?>


});

// 3SD Code Script Run after Required JS Load


var ScriptLoaded = document.createEvent('Event');
ScriptLoaded.initEvent('ScriptContentLoaded', true, true);
var script = Array.prototype.slice.call(document.querySelectorAll('script[data-required]'),0);
script.forEach(function(scrp , index){
	scrp.addEventListener("load", function(event) {
		if(script.length == index+1){
			document.dispatchEvent(ScriptLoaded);
		}
	});
});
if(script.length === 0){
	document.dispatchEvent(ScriptLoaded);
}
</script>
<?php

if(isset($_SESSION["productSliderIds"])){
	unset($_SESSION["productSliderIds"]);
}

	//---  Unset Sliders Id array (set it filterproducts/list.phtml)...
	Mage::getSingleton('core/session')->unsSliderIdArray();


?>
