<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Multishipping checkout billing information
 *
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>

<div class="row">
    <div class="col-sm-12">
        <div class="page-title">
            <h1><?php echo $this->__('Billing Information') ?></h1>
        </div>
		
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <script src="<?php echo Mage::getBaseUrl('js') ?>varien/payment.js" type="text/javascript"></script>
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="multishipping-billing-form">
					<div class="row">
						<div class="col-sm-6">
							<div class="box">
								<div class="box-title">
									<div class="btn-title">
									<div class="title-left">
									<h5><?php echo $this->__('Billing Address') ?></h5>
									</div>
									<div class="title-right">
									<h5><a class="icon-edit" href="<?php echo $this->getSelectAddressUrl() ?>" title="<?php echo $this->__('Change') ?>"><span class="hide"><?php echo $this->__('Change') ?></span></a></h5>
									</div>
									</div>
								</div>
							<div class="box-content">
								<?php $_address=$this->getAddress() ?>
								<address><?php echo $_address->format('html') ?></address>
							</div>
						</div>
                    </div>
                    <div class="col-sm-6">
						<div class="box">
							<div class="box-title">
								<h5><?php echo $this->__('Payment Method') ?></h5>
							</div>
							<div class="box-content">
                        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                            <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
                            <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                        </div>
                        <!-- Payment methods forms list -->
						<div class="payment-methods">
                        <dl class="sp-methods" id="co-payment-form">
                        <?php
                            $_methods       = $this->getMethods();
                            $_methodsCount  = count($_methods);
                        ?>
                        <?php foreach ($_methods as $_method): $_code = $_method->getCode() ?>
                            <dt id="dt_method_<?php echo $_code ?>">
                                <?php if ($_methodsCount > 1): ?>
                                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="with-gap" />
                                <?php else :?>
                                <span class="no-display"><input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" checked="checked" class="with-gap" /></span>
                                <?php endif;?>
                                <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($_method->getTitle()) ?>
									<?php if($_code == "cryozonic_stripe"): ?>
										<ul class="p-icon-list">
											<li><span class="p-icon icon-american-express icon-american-express-dims"></span></li>
											<li><span class="p-icon icon-diners-club icon-diners-club-dims"></span></li>
											<li><span class="p-icon icon-discover icon-discover-dims"></span></li>
											<li><span class="p-icon icon-jcb icon-jcb-dims"></span></li>
											<li><span class="p-icon icon-visa icon-visa-dims"></span></li>
											<li><span class="p-icon icon-master-card icon-master-card-dims"></span></li>
										</ul>
									<?php elseif($_code == "banktransfer"): ?>
										<ul class="p-icon-list">
											<li><span class="p-icon icon-bank-transfer-2 icon-bank-transfer-2-dims"></span></li>
											<?php if($storeCode == 'pk'): ?>
											<?php endif;?>
										</ul>
									<?php endif; ?>
								</label>
                            </dt>
                            <?php if($html = $this->getChildHtml('payment.method.'.$_code)) : ?>
                            <dd>
                                <?php echo $html; ?>
                            </dd>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </dl>
						</div>
                        <?php echo $this->getChildHtml('checkout_billing_items') ?>
						</div>
						</div>
                    </div>
                </div>
				
				<div class="buttons-set">
						<p class="back-link"><a class="arrow-left" href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('Back to Shipping Information') ?></a></p>
                        <button id="payment-continue" type="submit" title="<?php echo $this->__('Continue to Review Your Order') ?>" class="btn"><span><span><?php echo $this->__('Continue to Review Your Order') ?></span></span></button>
                    </div>
				
					 <?php echo $this->getBlockHtml('formkey') ?>
                
            </form>
			</div>
        
</div>

<script type="text/javascript">
//<![CDATA[
    var payment = new paymentForm('multishipping-billing-form');
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            /*$('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-510)+'px',
                left: (Event.pointerX(event)-800)+'px'
            })*/
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });

    // fix inputbox behaviour for payment forms injected via ajax
    document.observe("dom:loaded", function() {
        jQuery('.input-box').has('select').addClass('input-box-select');
        jQuery('.input-box').has('select').parent().addClass('select-list');
        jQuery('#multishipping-billing-form .input-box').addClass('fade-label');
        jQuery('.input-box-select').find('select').show();
        jQuery('.input-box-select').find('.chosen-container').hide();
        jQuery("select").each(function(){
            jQuery(this).on('change', function() {
                jQuery(this).siblings('.validation-advice').hide(300);
            });
        });
    });
//]]>
</script>
