<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <input type="hidden" name="remove" id="remove-coupone" value="0" />
    <div class="discount">
        <h2><?php echo $this->__('Discount Codes') ?></h2>
        <div class="discount-form">
            <ul class="form-list">
                <li class="row">
                    <div class="col-sm-12">
                    <div class="input-field input-wrapper">
						<label for="coupon_code" class="label-floating"><?php echo $this->__('Enter Coupon Code') ?></label>	
                        <input type="text" class="input-text input-floating" id="coupon_code" placeholder="<?php echo $this->__('Enter Coupon Code') ?>" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
						<button type="submit" title="<?php echo $this->__('Apply') ?>" class="btn-discount" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    </div>
					</div>
                </li>
            </ul>
            <div class="buttons-set">
                <?php if(strlen($this->getCouponCode())): ?><button type="submit" title="<?php echo $this->__('Cancel') ?>" class="btn-big btn" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button><?php endif;?>
            </div>
        </div>
    </div>
</form>
<style>
.discount-form .buttons-set {	
    margin: 0 0 0;
    padding-top: 0;
}
</style>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
