<div class="mini-cart">
	<form action="<?php echo $this->getUrl('checkout/cart/ajaxUpdate'); ?>" method="post" id="mini_cart_update">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?>
	<div class="dropdown-title"><?php echo $this->__('My Cart (%s)', $_cartQty); ?>
		<a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="icon-edit" title="<?php echo $this->__('Edit your Cart'); ?>">
			<span class="hide"><?php echo $this->__('Edit Cart'); ?></span>
		</a>
	</div>
    <span class="cart-qty hide"><?php echo $_cartQty ?></span>
		<?php $_items = $this->getRecentItems() ?>
		<?php if(count($_items)): ?>
				<div class="mini-products-wrapper">
					<div class="mini-products-container">
						<ul id="cart-sidebar" class="mini-products-list">
						<?php $i=0; 
						foreach($_items as $_item): ?>
							<?php if ($i != 0 && $i % 5 == 0): ?>
						</ul>
						<ul id="cart-sidebar" class="mini-products-list">
							<?php endif; ?>
							<?php echo $this->getItemHtml($_item) ?>
							<?php $i++; ?>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
		<?php else: ?>
			<p class="small cart-empty"><?php echo $this->__('Your shopping cart is currently empty.') ?></p>
			<button class="hide" type="submit">Submit</button>
		<?php endif ?>

			<div class="bg-box bg-border">
				<p class="subtotal">
					<?php echo $this->__('Subtotal:') ?>&nbsp;
					<?php if ($this->canApplyMsrp()): ?>
						<span class="price" title="<?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>">
							[?]
						</span>
					<?php else: ?>
						<span class="price">
							<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
								<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>
							<?php else: ?>
								<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
							<?php endif; ?>
						</span>
					<?php endif; ?>
				</p>
				<?php if($_cartQty && $this->isPossibleOnepageCheckout()){ ?>
				<?php  if(Mage::getSingleton('customer/session')->isLoggedIn() || !Mage::getStoreConfig('onestepcheckout/general/active',  Mage::app()->getStore())){?>
				<?php  $checkoutUrl = Mage::getStoreConfig('onestepcheckout/general/active', Mage::app()->getStore())==1?$this->helper('onestepcheckout')->getCheckoutUrl():$this->getCheckoutUrl();?>
					<a href="<?php echo $checkoutUrl; ?>" class="button sign-in"><?php echo $this->__('Checkout') ?></a>
				<?php }else{?>
					<a data-reveal-id="myModal" id="minicart_checkout" onclick="jQuery('#guest-checkout-button').show();" class="button sign-in"><?php echo $this->__('Checkout') ?></a>
				<?php } ?>
				<?php } ?>
				<div class="sb-cart-dropdown">
					<?php echo $this->getChildHtml('cart_promotion') ?>
				</div>
			</div>
			<?php echo $this->getBlockHtml('formkey') ?>
	</form>
</div>
<script type="text/javascript">
var productAddToCartFormMini;
var myHTML = document.querySelector('.cart-qty');
document.getElementById('cart-qty').innerHtml = myHTML;

if(document.readyState === "complete"){
	productAdd();
}
document.addEventListener("DOMContentLoaded", function() {				
	productAdd();
});
			
			
function productAdd(){			
				 //<![CDATA[
			productAddToCartFormMini = new VarienForm('mini_cart_update');
			productAddToCartFormMini.submit = function(button, url, customQtyId, buttonId, flag) {
				console.log(myHTML);
				if (this.validator.validate()) {
						
				//===================ZEE CODE===========//
				
					//if flag value is null or empty it means user has directly edited the cart
					
					if(flag != "" && flag != null){
						document.getElementById(buttonId+"_minicart_plus").disabled = "disabled";
						document.getElementById(buttonId+"_minicart_minus").disabled = "disabled";
						document.getElementById(buttonId+"_"+flag).style.background = "#01B4E5";
						if(flag=="minicart_minus"){
						
						document.getElementById(buttonId+"_minicart_plus").style.background = "#CCCCCC";
							var newCustomQtyVal = parseInt(document.getElementById(customQtyId).value)-1;
							document.getElementById(customQtyId).value = newCustomQtyVal;
						}else if(flag=="minicart_plus"){
						document.getElementById(buttonId+"_minicart_minus").style.background = "#CCCCCC";
							var newCustomQtyVal = parseInt(document.getElementById(customQtyId).value)+1;
							document.getElementById(customQtyId).value = newCustomQtyVal;
						}
					}else{
					
						document.getElementById(buttonId+"_minicart_plus").disabled = "disabled";
						document.getElementById(buttonId+"_minicart_minus").disabled = "disabled";
						document.getElementById(buttonId+"_minicart_plus").style.background = "#01B4E5";
						document.getElementById(buttonId+"_minicart_minus").style.background = "#01B4E5";
					}
				//===================END ZEE CODE===========//	
				
					var form = this.form;
					var oldUrl = form.action;

					if (url) {
					   form.action = url;
					}
					
					var e = null;
					if (!url) {
						url = jQuery('#mini_cart_update').attr('action');
					  
					}
					if(url.indexOf("wishlist/index/cart") != -1){
						url = url.replace("wishlist/index/cart","ajaxcart/index/add"); // New Code
					} else {
						
						url = url.replace("checkout/cart","ajaxcart/index"); // New Code
					}
					url = url.replace("http://", "//");
					url = url.replace("https://", "//");
					var data = jQuery('#mini_cart_update').serialize();
					data += '&isAjax=1';
					var is_quickview = false;
					if(jQuery("body").hasClass("quickview-index-view")){
						is_quickview = true;
					}
					if(is_quickview)
						window.parent.jQuery("#loading-mask").show();
					else
							
						
					try {
						
						jQuery.ajax({
							url : url,
							dataType : 'json',
							type : 'post',
							data : data,
							success : function(data) {
								if(is_quickview)
									window.parent.jQuery('#loading-mask').hide();
								else
									jQuery('#loading-mask').hide();
								if(data.status == 'ERROR'){
									if(is_quickview)
										window.parent.alert(data.message.replace("<br/>",""));
									else
										alert(data.message.replace("<br/>",""));
								}else{
									if(is_quickview){
										
										if(window.parent.jQuery('.main-header .mini-cart')){
											window.parent.jQuery('.main-header .mini-cart').replaceWith(data.toplink);
										}
									
										if(window.parent.jQuery('.col-right .block.block-cart')){
											window.parent.jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
										}
										window.parent.jQuery('#after-loading-success-message .msg-box').html(data.message);
										<?php $code = Mage::app()->getStore();?>
										<?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
										ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
										timer_sec = ajaxcart_sec;
										window.parent.jQuery('#after-loading-success-message').fadeIn(200);
										ajaxcart_timer = setInterval(function(){
											timer_sec --;
											window.parent.jQuery('#after-loading-success-message .timer').html(timer_sec);
										},1000)
										setTimeout(function(){
											window.parent.jQuery('#after-loading-success-message').fadeOut(200);
											clearTimeout(ajaxcart_timer);
											setTimeout(function(){
												window.parent.jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
											}, 1000);
										},ajaxcart_sec*1000);
									}
									else {
										
								
									//var myHTML = jQuery('.cart-qty').html();
									//============== ZEE CODE=====================// 
										//--- Getting Cart Items Count From Server Side on Cart Page & Not Displaying MiniCart on Hover 	
										jQuery('#cart-qty').html(data.cart_count);
									//============== ZEE CODE=====================// 
										if(jQuery('.main-header .mini-cart')){
											jQuery('.main-header .mini-cart').replaceWith(data.toplink);
										}
										if(jQuery('.cart ')){
											jQuery('.cart ').replaceWith(data.shoping_cart);
										}
										if(jQuery('.fixed-header .mini-cart')){
											jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
										}
										if(jQuery('.sticky-header .mini-cart')){
											jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
										}
										if(jQuery('.col-right .block.block-cart')){
											jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
										}
										
										jQuery('#after-loading-success-message .msg-box').html(data.message);
										<?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
										ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
										timer_sec = ajaxcart_sec;
										jQuery('.topCartContent').show();
										ajaxcart_timer = setInterval(function(){
											timer_sec --;
											jQuery('#after-loading-success-message .timer').html(timer_sec);
										},1000);
										
									 
										if(jQuery('#shopping-cart-table').find('td > p.error').html()){
											jQuery('.col-xs-9>.page-title').after('<ul class="messages"><li class="error-msg"><ul><li><span>Some of the products cannot be ordered in requested quantity.</span></li></ul></li></ul>');
										}else{
											jQuery('.col-xs-9>.page-title').after('');
									
										}
									}
									
								}
							}
							
						});
					} catch (e) {
					} 
		
					this.form.action = oldUrl;
					if (e) {
						throw e;
					}
				}
			}.bind(productAddToCartFormMini);
					
		//]]>
		
		//--- Minicart Checkout Popup Initialization ....
		jQuery('#minicart_checkout').on('click', function(){
			jQuery('#myModal').addClass('guest-popup');
			jQuery('#create-acount-action').hide();
			jQuery('#myModal.guest-popup').removeClass('guest-forget-popup');

			//--- Reset any validations for Forgot Password Form
			var forgotPasswordForm = new VarienForm('social-forgot-pass');
			forgotPasswordForm.validator.reset();
			
			//--- Reset any validations for Sign in/Login Form
			var userLoginForm = new VarienForm('login-form');
			userLoginForm.validator.reset();
			
			//--- Reset any validations for Signup/Register Form
			var userRegisterForm = new VarienForm('social-register-form');
			userRegisterForm.validator.reset();
			
			//--- intitialize Popup with Login Form (hide other forms)
			jQuery('#account-forgotpassword').hide();
			jQuery('#account-create').hide();
			jQuery('#login-form').show();
			jQuery('.tejar-socialconnect-login').show();
			jQuery('#send-friend').hide();
			
			//--- Hide Messages and Guest checkout button as it is Signup link not BuyNow.
			jQuery('#myModal .messages').hide();

		});
}


</script>
 