<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
$_jsonConfig = $this->getJsonConfig();
$_renderers  = $this->getChild('attr_renderers')->getSortedChildren();
?>
<?php /*=========================**** ZEE CODE ***==============================*/
	$moduleName = Mage::app()->getRequest()->getModuleName();

	//--- Store Product Attributes Count in a Hidden Field to be used in Swatch Js...  
	$myConfigProductAttributeCount = count($_attributes);
	echo '<input type="hidden" id="myConfigProductAttributeCount" value="'.$myConfigProductAttributeCount.'" />';

	/*=========================**** END ZEE CODE ***=============================*/
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute):
//echo "<pre>"; var_dump($_attribute); die;	
?>
    <?php
        $_rendered = false;
        foreach ($_renderers as $_rendererName):
            $_renderer = $this->getChild('attr_renderers')->getChild($_rendererName);
            if (method_exists($_renderer, 'shouldRender') && $_renderer->shouldRender($_attribute, $_jsonConfig)):
                $_renderer->setProduct($_product);
                $_renderer->setAttributeObj($_attribute);
                echo $_renderer->toHtml();
                $_rendered = true;
                break;
            endif;
        endforeach;
	?>
        <?php if(!$_rendered):?>
        <dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
        <?php endif; ?>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
		var spConfig;
		document.addEventListener("DOMContentLoaded", function(){
			spConfig = new Product.Config(<?php echo $_jsonConfig ?>);
			
		});
    </script>
    <?php echo $this->getChildHtml('after') ?>
<?php endif;?>
