<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();

?>
<a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
</a>
<h2 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h2>
<div class="description std"><div class="inner"><?php //echo $this->escapeHtml($this->stripTags($product->getShortDescription()));?></div></div>
<?php if($this->getSortedChildren()): ?>
    <div class="item-manage">
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    </div>
<?php endif; ?>
<div class="input-field input-wrapper">
<label class="label-floating"><?php echo $this->helper('wishlist')->defaultCommentString(); ?></label>
<div class="input-box textarea">
	<textarea class="text-area input-floating" name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" placeholder="<?php echo $this->helper('wishlist')->defaultCommentString();?>"  title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>
</div>
</div>
