<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<?php if ($product->isSaleable()): ?>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="btn-floating blue"><i class="icon-cart"></i></button>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        
    <?php else: ?>
        
    <?php endif; ?>
<?php endif; ?>
</div>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="btn-floating green" href="<?php echo $this->getItemConfigureUrl($item) ?>"><i class="icons-pencil"></i></a>
<?php endif ?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove Item') ?>"
    class="btn-floating red"><i class="icons-cancel-2"></i></a>