<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();

?>
<td class="item-image-col">
<a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
    <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(150); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
</a>
<?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
    <div id="qty-wrapper-<?php echo $item->getId() ?>" class="qty-wrapper" style="text-align: center;">
        <?php if (($this->getAddToCartQty($item) * 1) < 10): ?>
            <select class="simulate-change" name="qty[<?php echo $item->getId() ?>]" id="qty[<?php echo $item->getId() ?>]">
                <?php for ($i=1; $i < 10; $i++): ?>
                    <option value="<?php echo $i ?>"<?php if (($this->getAddToCartQty($item) * 1) == $i): ?> selected="selected"<?php endif; ?>><?php echo $i ?></option>
                <?php endfor; ?>
                <option value="10">10+</option>
            </select>
            <script type="text/javascript">
                $("qty[<?php echo $item->getId() ?>]").observe('change', function(){
                    if ($(this).getValue() == 10) {
                        $("qty-wrapper-<?php echo $item->getId() ?>").update('<input type="number" class="input-text qty validate-not-negative-number" name="qty[<?php echo $item->getId() ?>]" size="4" maxlength="10" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />');
                    }
                });
            </script>
        <?php else: ?>
            <input name="qty[<?php echo $item->getId() ?>]" id="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" />
        <?php endif; ?>
    </div>
<?php endif; ?>
</td>
<td>
<h5 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h5>
<div class="description std"><div class="inner"><?php //echo $this->escapeHtml($this->stripTags($product->getShortDescription()));?></div></div>
<?php if($this->getSortedChildren()): ?>
    <div class="qty_price">
    <?php foreach($this->getSortedChildren() as $childName):?>
        <?php echo $this->getChildHtml($childName, false);?>
    <?php endforeach;?>
    </div>
<?php endif; ?>
<div class="btn_action_col">
<?php if ($product->isSaleable()): ?>
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="btn-floating blue"><i class="icon-cart"></i></button>
<?php /*else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php */ endif; ?>
<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="btn-floating green" href="<?php echo $this->getItemConfigureUrl($item) ?>"><i class="icons-pencil"></i></a>
<?php endif ?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove Item') ?>"
    class="btn-floating red"><i class="icons-cancel-2"></i></a>
</div>
<div class="input-field input-wrapper">
<label class="label-floating"><?php echo $this->helper('wishlist')->defaultCommentString(); ?></label>
<div class="input-box textarea">
	<textarea class="text-area input-floating" name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" placeholder="<?php echo $this->helper('wishlist')->defaultCommentString();?>"  title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>
</div>
</div>

</td>
