<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

	
<div class="row row-margin-5">
	<div class="col-xs-6">		
		<div class="account-form-box min-height-175">
			<h5 class="mbottom-0"><?php echo $this->__('Default Billing Address') ?></h5>
			<a class="fsize-14 mbottom-10 block" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><span><?php echo $this->__('Edit Address') ?></span></a>
			<address>
				<?php echo $this->getPrimaryBillingAddressHtml() ?>
			</address>
		</div>
	</div>
	
	<div class="col-xs-6">
		<div class="account-form-box min-height-175">
			<h5 class="mbottom-0"><?php echo $this->__('Default Shipping Address') ?></h5>
			<a class="fsize-14 mbottom-10 block" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><span><?php echo $this->__('Edit Address') ?></span></a>
			<address>
				<?php echo $this->getPrimaryShippingAddressHtml() ?>
			</address>
		</div>
	</div>
</div>

	