<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

<div class="row">
    <div class="guest-order-status col-xs-12">
       
		<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
		 <div class="page-title">
            <h1><?php echo Mage::helper('sales')->__('Orders and Returns') ?></h1>
        </div>
		<div class="account-form-box">
        <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
            <div class="">
                <!--<h2 class="legend"><?php // echo Mage::helper('sales')->__('Order Information') ?></h2>-->

                <ul class="form-list row">
                    <li>
					<div class="input-field input-wrapper">
                        <label for="oar_order_id" class="required label-floating"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
                       <div class="input-box">
                           <input type="text" class="input-text required-entry input-floating" placeholder="<?php echo Mage::helper('sales')->__('Order ID') ?>" id="oar_order_id" name="oar_order_id"/>
                       </div>
					   </div>
                    </li>
                    <li class="wide">
                        <p class="legend">
                            <?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.
                        </p>
                    </li>
					<li>
						<div class="input-field input-wrapper select-wrapper chosen-wrapper">
							<label class="required chosen-label"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
							<div class="input-box">
								<select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
									<option value="email">Email Address</option>
									<option value="zip">ZIP Code</option>
								</select>
							</div>
							</div>
						
                    </li>
                    <li>
						<div class="input-field input-wrapper">
							<label for="oar_billing_lastname" class="required label-floating"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
							<div class="input-box">
								<input type="text" class="input-text required-entry input-floating" placeholder="<?php echo Mage::helper('sales')->__('Billing Last Name') ?>" id="oar_billing_lastname" name="oar_billing_lastname" />
							</div>
						</div>
                    </li>
                    
                    <li  id="oar-email">
						<div class="input-field input-wrapper">
							<label for="oar_email" class="required label-floating"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
							<div class="input-box">
								<input type="text" class="input-text validate-email required-entry input-floating" placeholder="<?php echo Mage::helper('sales')->__('Email Address') ?>" id="oar_email" name="oar_email" />
							</div>
						</div>
                    </li>
                    <li id="oar-zip" style="display:none;">
						<div class="input-field input-wrapper">
							<label for="oar_zip" class="required label-floating"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
							<div class="input-box">
								<input type="text" placeholder="<?php echo Mage::helper('sales')->__('Billing ZIP Code') ?>" class="input-text required-entry input-floating" id="oar_zip" name="oar_zip"/>
							</div>
						</div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <button type="submit" title="<?php echo Mage::helper('sales')->__('Continue') ?>" class="btn"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
            </div>
        </form>
		</div>
		</div>
		</div>
		
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
	//==================================================== ZEE CODE ============================================//
	/*
	*@name   SubmitAndTrimValues
	*@params formID
	*@return none (trims whitespaces from form values)
	*/
	function SubmitAndTrimValues(formIdToSubmit){
		
		jQuery('#'+formIdToSubmit+' *').filter(':input',':textarea').each(function(){
			if(jQuery(this).attr('id')=="oar_order_id" || jQuery(this).attr('id')=="oar_billing_lastname" || jQuery(this).attr('id')=="oar_email" || jQuery(this).attr('id')=="oar_zip"){
				this.value=jQuery(this).val().trim();
			}
		});
			//--- Validate address form before submitting....
			
			var validator = new Validation(formIdToSubmit);
			if(validator.validate()){
				
				setTimeout(function(){
					jQuery('#'+formIdToSubmit).submit();
				},500);
			}
	}
	
/*jQuery(document).ready(function(){
	//--- Trigger Submit Event upon pressing ENTER Key..
	jQuery('#oar_widget_orders_and_returns_form').bind('keyup', function (e) {
		if(e.which == 13){
			//if(jQuery('#myModal').css('display')=="none"){
				return SubmitAndTrimValues('oar_widget_orders_and_returns_form');
			//}
		}
	});
});*/
</script>
