<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

<?php
$_product = $this->getProduct();
$_description = $_product->getDescription();
$_recurring = $_product->getRecurringProfile();
$_attributes = new Mage_Catalog_Block_Product_View_Attributes();
$_attributes->setProduct($_product->getId());
$_additional = $_attributes->getAdditionalData();
$_customInfo = Mage::getModel('cms/block')->getCollection()->addStoreFilter(Mage::app()->getStore()->getId(), true)->addFieldToFilter('identifier', 'product_view_block_3')->getFirstItem();
$themeHelper = Mage::helper('itactica_intenso');
$_inTheBox = $_product->getData('in_the_box');
?>
<ul class="">
        <?php if ($_description || $_inTheBox): ?>
          <li class="custom_tab" id="tab_description_tabbed"><a onclick="javascript:csTablist.remoteTabs('tab_description_tabbed');"  href="javascript:void(0)"><?php echo $this->__('Product Description'); ?></a></li>
        <?php endif; ?>
		 <?php if ($_additional): ?>
         <li class="custom_tab" id="tab_additional_tabbed"><a onclick="javascript:csTablist.remoteTabs('tab_additional_tabbed');"  href="javascript:void(0)"><?php echo $this->__('Additional Info'); ?></a></li>
        <?php endif; ?>
		<?php if (Mage::helper('core')->isModuleOutputEnabled('Mage_Review') &&
            Mage::helper('core')->isModuleOutputEnabled('Itactica_ExtendedReviews')): ?>
           <li id="tab_ratings-reviews_tabbed" class="<?php if (!Mage::helper('core')->isModuleOutputEnabled('Mage_Tag') and !$_customInfo->getIsActive() and  !$_recurring and $_description ): ?>list-full<?php endif; ?> custom_tab"><a onclick="javascript:csTablist.remoteTabs('tab_ratings-reviews_tabbed');" href="javascript:void(0)"><?php echo $this->__('Ratings & Reviews'); ?></a></li>	
        <?php endif; ?>	
		<?php if ($_recurring): ?>
         <li id="tab_recurring_info_tabbed"><a onclick="javascript:csTablist.remoteTabs('tab_recurring_info_tabbed');"  href="javascript:void(0)"><?php echo $this->__('Recurring Info'); ?></a></li>
        <?php endif; ?>
		<?php if (Mage::helper('core')->isModuleOutputEnabled('Mage_Tag')): ?>
           <li id="tab_tags_tabbed" class="<?php if(!$_customInfo->getIsActive() and $_recurring):?>list-full<?php endif;?> custom_tab"><a onclick="javascript:csTablist.remoteTabs('tab_tags_tabbed');" href="javascript:void(0)"><?php echo $this->__('Tags'); ?></a></li>
        <?php endif; ?>								
		 <?php if ($_customInfo->getIsActive()): ?>
			<li  id="tab_custom_tabbed" class="<?php if(Mage::helper('core')->isModuleOutputEnabled('Mage_Tag') and !$_recurring or $_recurring and !Mage::helper('core')->isModuleOutputEnabled('Mage_Tag')):?>list-full<?php endif;?> custom_tab"><a onclick="javascript:csTablist.remoteTabs('tab_custom_tabbed');" href="javascript:void(0)"><?php echo $this->__('Custom Info'); ?></a></li>
        <?php endif; ?>								

</ul>
<script type="text/javascript">
var tabs = document.querySelectorAll('.product-tabs li');
if(tabs.length !== 0){
	tabs[0].classList.add('active');
}
</script>
<div class="clearer"></div>