<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('login_before')?>
<div class="row">
    <div class="col-sm-6 right-line">
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
			
            <div class="login-box">
				<h4 class="subcaption"><?php echo $this->__('Registerd Customers') ?></h4>
				<p class=""><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul class="form-list">
                    <li class="">
						<div class="input-field input-wrapper">
							<label for="login-email" class="required label-floating"><?php echo $this->__('Email Address') ?></label>
							<div class="input-box">
								<input type="email" class="input-text input-floating required-entry validate-email" placeholder="<?php echo $this->__('Email Address') ?>" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
							</div>
						</div>
                    </li>

                    <li>
						<div class="input-field input-wrapper">
						
							<label for="login-password" class="required label-floating"><?php echo $this->__('Password') ?></label>
							<div class="input-box">
								<input type="password" class="input-text input-floating required-entry" placeholder="<?php echo $this->__('Password') ?>" id="login-password" name="login[password]" />
							</div>
							<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forget_link"><?php echo $this->__('forgot?') ?></a>
						</div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <input name="context" type="hidden" value="checkout" />
				</div>
                <div class="buttons-set">
                    <button type="submit" class="btn btn-big" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            
        </form>
    </div>
	
	</br>
	
    <div class="col-sm-6">
		<div class="register-box">
			<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
			<h4 class="subcaption"><?php echo $this->__('Checkout as Guest or Register') ?></h4>
				<ul class="form-list">
					<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
					<li class="control">
						<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
					</li>
					<?php endif; ?>
					<li class="control">
						<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
					</li>
				</ul>
			<?php else: ?>
				<input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
			<?php endif; ?>
			<h4 class="subcaption"><?php echo $this->__('Register and save time!') ?></h4>
			<ul class="list_type_7">
				<li>Fast and easy check out</li>
				<li>Easy access to your order history and status</li>
			</ul>
		</div>
		<div class="buttons-set row">
			<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="btn btn-big " onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="btn btn-big " onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="btn btn-big "><span><span><?php echo $this->__('Register') ?></span></span></button>
                </form>
            <?php endif; ?>
			
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
