<div class="hide" id="cmsDate">
	<span id="longDate" class=""><?php echo Mage::getModel('core/date')->date('Y-m-d H:i:s'); ?></span><br>
	<span id="time24" class=""><?php echo Mage::getModel('core/date')->date('H:i:s'); ?></span><br>
	<span id="Date" class=""><?php echo Mage::getModel('core/date')->date('Y-m-d'); ?></span><br>
	<span id="time12" class=""><?php echo Mage::getModel('core/date')->date('h:i:s'); ?></span><br>
	<span id="time12With_AM_PM" class=""><?php echo Mage::getModel('core/date')->date('g:i:s A'); ?></span><br>
	<span id="time_am_pm" class=""><?php echo Mage::getModel('core/date')->date('a'); ?></span><br>
	<span id="time_AM_PM" class=""><?php echo Mage::getModel('core/date')->date('A'); ?></span><br>
</div>