<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

<?php if (Mage::helper('itactica_quickview')->isEnabled()): ?>
<?php if(Mage::getStoreConfig('onestepcheckout/general/active',  Mage::app()->getStore())==0 || Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<div id="myModal" class="guest-popup reveal-modal small-customer-popup" data-reveal aria-hidden="true" role="dialog">
</div>
<?php endif; ?>
<div id="quickview-modal" class="reveal-modal quickview-modal" data-reveal aria-hidden="true" role="dialog">
	<a class="close-reveal-modal" aria-label="Close">×</a>
	<div class="row quickview-content"></div>
	
</div>
<script>
var count = 0;	
</script>

<?php endif; ?>
