<?php
	$storePhone = Mage::getStoreConfig('general/store_information/phone');
	$whatsappNumber = Mage::getStoreConfig('intenso/contact/whatsapp_contact_number', Mage::app()->getStore());
	$whatsappTitle = Mage::getStoreConfig('intenso/contact/whatsapp_contact_title', Mage::app()->getStore());
?>
<?php if($storePhone): ?>
<table align="right" <?php if($whatsappTitle): ?>width="40%"<?php else: ?>width="100%"<?php endif; ?> border="0" cellspacing="0" cellpadding="0" style="max-width: 150px;" class="columnWrapper"><tbody><tr><td align="center" valign="middle" height="18" width="18" style="width:35px; height:28px;"><img style="display:block" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/phone-call-button.png" alt="Call" width="18" height="18" border="0"></td><td align="left" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:16px; color:#444444;"><span style="font-weight: normal;color:#656565; text-decoration:none;"><?php echo $storePhone; ?></span></td></tr></tbody></table>
<?php endif; ?>
<?php if($whatsappTitle): ?>
<table align="right" <?php if($storePhone): ?>width="60%"<?php else: ?>width="100%"<?php endif; ?> border="0" cellspacing="0" cellpadding="0" style="max-width: 150px;" class="columnWrapper"><tbody><tr><td align="center" valign="middle" height="18" width="18" style="width:35px; height:28px;"><img style="display:block" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/email/whatsapp.png" alt="Whatsapp" width="18" height="18" border="0"></td><td align="left" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:16px; color:#444444;"><span style="font-weight: normal;color:#656565; text-decoration:none;"><?php echo $whatsappTitle; ?></span></td></tr></tbody></table>
<?php endif; ?>
