<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
    <nav class="layered-nav-container top-bar left-off-canvas-menu main-nav<?php if(Mage::getStoreConfig('itactica_layerednavigation/catalog/layered_nav_expanded')): ?> open<?php endif; ?><?php if(Mage::getStoreConfig('itactica_layerednavigation/catalog/remember_filter_display')): ?> remember<?php endif; ?> is_anchor ajax_filter"  data-topbar>
        <?php // static block - top ?>
        <?php if (Mage::getModel('cms/block')->load('layered_nav_top_block')->getIsActive()): ?>
            <div class="layered-nav-top-block">
                <?php echo $this->getChildHtml('layered_nav_top_block') ?>
            </div>
        <?php endif; ?>
        <?php // filter reset link ?>
        <span id="filter-reset">
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <a href="<?php echo $this->getClearUrl() ?>" class="filter-reset"><?php echo $this->__('Reset Filters') ?></a>
        <?php endif; ?>
        </span>
        <?php // layered navigation ?>
        <section class="layered-nav top-bar-section">
		<h3 style="display:none;">Category Attributes</h3>
            <?php echo $this->getChildHtml('product_list_sorter'); ?>
            <div id="layered-navigation" class="block-content">
				<dl id="narrow-by-list">
					<?php for($i = 0; $i <= 7; $i++): ?>
						<dl>
							<div class="ph-item">
							  <div class='text-input__loading'>
								<?php for($x = 0; $x <= 5; $x++): ?>
								  <div class='text-input__loading--line'></div>
								<?php endfor; ?>	
								</div>
							</div>
						</dl>
					<?php endfor; ?>
				</dl>
    <?php endif; ?>
			<?php if ($this->getRequest()->isAjax()): ?>
                <?php echo $this->getStateHtml() ?>
                <?php if($this->canShowOptions()): ?>
                    <dl id="narrow-by-list">
                        <?php $_filters = $this->getFilters() ?>
                        <?php foreach ($_filters as $_filter): ?>
                        <?php if($_filter->getItemsCount()): ?>
                            <dt><?php echo $this->__($_filter->getName()) ?></dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                <?php endif; ?>
			<?php endif; ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
            </div>
            <?php // static block - bottom ?>
            <?php if (Mage::getModel('cms/block')->load('layered_nav_bottom_block')->getIsActive()): ?>
                <div class="layered-nav-bottom-block">
                    <?php echo $this->getChildHtml('layered_nav_bottom_block') ?>
                </div>
            <?php endif; ?>
        </section>
    </nav>
    <?php endif; ?>
<?php else: ?>
<style>
.filter-toggle,
.layered-nav-toggle{
	display: none !important;
}
.tejar #catalog-listing,
.tejar-tablet #catalog-listing{
	margin-left: 8px !important;
}
.tejar-mobile #catalog-listing{
	margin-left: 0px !important;
}
    
</style>
<?php endif; ?>

