<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
    $_intensoHelper = $this->helper('itactica_intenso');
	$store = Mage::app()->getStore();
	$showHideAddToCart = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', $store);
	$showHideAddToCartList = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', $store);
	$_isNewLabel = Mage::getStoreConfig('intenso/product_label/new_label', Mage::app()->getStore());
	$_isSaleLabel = Mage::getStoreConfig('intenso/product_label/sale_label', Mage::app()->getStore());
?>

<?php $headingTitle = Mage::getStoreConfig('design/product_meta/category_h1_title', Mage::app()->getStore()->getId()); ?>

<?php $collectionLabel = $this->getLabels(); ?>

<?php if(!$_productCollection->getSize()): ?>
    <?php $emptyCollectionBlock = $this->getLayout()->createBlock('cms/block')->setBlockId('category_empty_collection')->toHtml(); ?>
	<?php
	$pageTile = $_category->getName();

	?>
  <?php if((empty($_category->getChildrenCategories()) && $_category->getCollectionType() == null) || $_category->getCollectionType() != null): ?>
	<div class="catalog-list-empty">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<h1 id="category-name" class="empty-catalog"><?php echo $pageTile; ?><?php echo $headingTitle != "" && $_category->getCollectionType() == null  ? "<span class='hide'>".$headingTitle."</span>":""; ?></h1>
            <?php if ($emptyCollectionBlock): ?>
                <?php echo $emptyCollectionBlock; ?>
            <?php else: ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
            <?php endif; ?>
				</div>
			</div>
		</div>
			<?php if ($emptyCollectionBlock): ?>
			<?php else: ?>
				<?php echo $this->getChildHtml('left.reports.product.viewed') ?>
			<?php endif; ?>
        </div>
    <?php if (!$this->getRequest()->isAjax() && Mage::helper('core')->isModuleOutputEnabled('Itactica_FeaturedProducts')): ?>
        <?php if (Mage::getStoreConfig('intenso/catalog/empty_category_featured')): ?>
            <?php echo $this->getLayout()->createBlock('itactica_featuredproducts/view')->setIdentifier(Mage::getStoreConfig('intenso/catalog/empty_category_featured'))->setTemplate('itactica_featuredproducts/view.phtml')->toHtml() ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php endif ?>
<?php else: ?>
<?php if (!$this->getRequest()->isAjax()): ?>
<div class="tejar-catalog">
<section class="products-grid clearfix" data-list-qty="<?php echo (int) Mage::getStoreConfig('itactica_layerednavigation/catalog/list_items_qty'); ?>">
	<div class="container">
    <div id="ajax-errors" style="display: none;">
        <ul class="ajax-message">
            <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
        </ul>
    </div>
    <?php echo $this->getToolbarHtml(); ?>
    <?php if($_description=$_category->getDescription()): ?>
        <div class="row category-description">
            <div class="col-sm-12">
                <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
            </div>
        </div>

    <?php endif; ?>
	</div>
    <?php echo $this->getChildHtml('catalog.leftnav'); ?>
    <?php echo $this->getChildHtml('catalogsearch.leftnav'); ?>
	<div class="category-container">
    <ul id="catalog-listing" class="category-products<?php if ($_intensoHelper->isKeepAspectRatio()): ?> keep-aspect-ratio<?php endif; ?><?php if ($this->helper('itactica_layerednavigation')->isAjaxEnabled()): ?> ajax<?php endif; ?><?php if ($_intensoHelper->isInfiniteScroll()): ?> infinite-scroll<?php endif; ?> clearfix <?php if($this->getMode()!='grid'): ?>list<?php endif; ?>">
<?php endif; ?>

<?php foreach ($_productCollection as $_product): ?>
	<?php
		/*--------------------------------------------------- 3SD CODE ------------------------------------------*/
		$product = $this->getCustomProduct($_product);
		$productUrl = $_product->getProductUrl();
		if($product->getTypeId()=="simple" && $product->getVisibility()==1){
			$parentIds = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($_product->getId());
			$parentId  = $parentIds[0];
			if($parentId!=null){
				$product    = Mage::getModel('catalog/product')->load($parentId);
				$productUrl = $product->getProductUrl();
			}
		}
		/*--------------------------------------------------- 3SD CODE ------------------------------------------*/
		//--- Get Custom Stock Status if Avialable............
		$customStock = $this->getCustomInStockStatus();
		$customStockStatusText = $customStock['stockStatusText'];
		$customInStockStatus = $customStock['inStockStatus'];
		/*---------------------------------------------------- 3SD CODE -------------------------------------------*/
		$isLazyLoading = Mage::getStoreConfig('intenso/catalog/lazy_loading' , $store);
	?>

        <li class="item isotope-item">
            <div class="item-content clearfix">
                <div class="item-images<?php if ($_intensoHelper->isFlushed()): ?> flush<?php endif; ?>">
                   <?php $width = 430; ?>
                    <?php $_height = Mage::getStoreConfig('intenso/catalog/catalog_product_height', Mage::app()->getStore()); ?>
                    <?php $height = $_intensoHelper->getImageHeight($_product, $width, $_height); ?>
					<?php $_width = 215; $_height = 202; ?>
                    <a class="product-image" href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo Mage::helper('itactica_intenso')->getPictureStyle() ; ?>>
                        <?php if ($isLazyLoading && $_intensoHelper->isKeepAspectRatio() == false): ?>
                             <img
							id="product-collection-image-<?php echo $_product->getId(); ?>"
							class="item-image lazyload"
							alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
							src="<?php echo $this->getSkinUrl('images/clear.png'); ?>"
							sizes="50vw"
							data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width , $_height); ?>"
							data-srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width,$_height); ?> 1200w,
							<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?> 1400w"
							width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                        <?php else: ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
							class="item-image"
							alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
							src="<?php echo $this->getSkinUrl('images/clear.png'); ?>"
							sizes="50vw"
							src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width , $_height); ?>"
							srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width,$_height); ?> 1200w,
							<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?> 1400w"
							width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                        <?php endif; ?>
						<?php echo $_intensoHelper->getSliderAlternativeImgUrl($_product, $width, $height , $isLazyLoading); ?>
                    </a>
					 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', $store)): ?>
                            <a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>

                            <?php endif; ?>
                        <?php endif; ?>

                    <div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel" data-source="category"></div>
                    <?php $_isNewAvailable = true; ?>
            					<?php if($_isNewLabel): ?>
            						<?php
            							$now = date("Y-m-d");
            							$newsFrom= substr($_product->getData('news_from_date'),0,10);
            							$newsTo=  substr($_product->getData('news_to_date'),0,10);
            						?>
            						<?php	if ($newsTo != '' || $newsFrom != ''): ?>
            							<?php	if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)): ?>
            								<?php $_isNewAvailable = false; ?>
            								<?php  if(isset($collectionLabel['New'])) echo $collectionLabel['New']; ?>
            							<?php endif; ?>
            						<?php endif; ?>
            					<?php endif; ?>
            					<?php if($_isSaleLabel && $_isNewAvailable && ($_product->getStockItem()->getIsInStock() && $customInStockStatus)): ?>
            						<?php
            							$now = date("Y-m-d");
            							$specialPrice = $_product->getSpecialPrice();
            							$newsFromSpecial = substr($_product->getData('special_from_date'),0,10);
            							$newsToSpecial =  substr($_product->getData('special_to_date'),0,10);
            						?>
            						<?php if ($newsToSpecial != '' || $newsFromSpecial != '' || $specialPrice != ''): ?>
            							<?php if (($newsToSpecial != '' && $newsFromSpecial != '' && $now>=$newsFromSpecial && $now<=$newsToSpecial) || ($newsToSpecial == '' && $now >=$newsFromSpecial) || ($newsFromSpecial == '' && $now<=$newsToSpecial)): ?>
            							<?php  if(isset($collectionLabel['Discount'])) echo $collectionLabel['Discount']; ?>
            							<?php endif; ?>
            						<?php endif; ?>
            					<?php endif; ?>
                    <?php if (Mage::helper('itactica_quickview')->isEnabled() && Mage::getStoreConfig('intenso/quickview/grid_enable', $store)): ?>
                    <a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
                    <?php endif;  ?>
					<?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', $store)) : ?>
					<a id="wish-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist-custom icons-heart-empty"></a>
					<?php endif; ?>
                </div>
                <div class="item-info">
					<h6 class="item-title">
					<?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
					<?php if(Mage::getStoreConfig('intenso/catalog/product_name_length', $store) == 4): ?>
                        <a href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span class="block truncate-name" id="full-name-<?php echo $_product->getId(); ?>"><?php echo $_productName ?></span></a>
					<?php else : ?>
                        <a href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="truncate"><span><?php echo $_productName ?></span></a>
					<?php endif; ?>
					</h6>
					 <h6 class="item-title list-title">
                        <a href="<?php echo $productUrl; ?>" class="" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span><?php echo $_productName; ?></span></a>
                    </h6>
					<?php if($_product->getAttributeText('manufacturer')):?>
						 <p class="brand-list">By:  <span class="by"><?php echo $_product->getAttributeText('manufacturer')?> </span></p>
					 <?php endif;?>
					  <?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', $store)): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
					<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', $store)): ?>
						<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>
                    <?php endif; ?>
					 	<?php if ($_product->getStockItem()->getIsInStock() && $customInStockStatus): ?>
							<p class="availability in-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo $customStockStatusText!=""?$customStockStatusText:"In Stock"?></span></p>
						<?php else :?>
							<p class="availability out-of-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo $customStockStatusText!=""?$customStockStatusText:"Out of Stock"?></span></p>
						<?php endif; ?>
                    <div class="item-description">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                    <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product price
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                    ?>
                     <?php if (Mage::helper('itactica_quickview')->isEnabled() && Mage::getStoreConfig('intenso/quickview/grid_enable', $store)): ?>
						<a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
                    <?php endif; ?>
                </div>
				<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', $store) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', $store) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', $store) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', $store) || Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', $store)): ?>
					<div class="actions clearfix <?php if($showHideAddToCart):?>grid-block<?php endif; ?> <?php if($showHideAddToCartList):?>list-block<?php endif; ?>">
						<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', $store)): ?>
							<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
								<?php echo $this->getLayout()->createBlock('catalog/product_price')->setTemplate('catalog/product/custom_clone_price.phtml')->setProduct($_product)->setDisplayMinimalPrice(true)->toHtml(); ?>
							<?php endif; ?>
						<?php endif; ?>
						<?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', $store)): ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif; ?>
						<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', $store) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', $store)): ?>
							<?php if(!$_product->canConfigure() && $_product->isSaleable() &&  $customInStockStatus == true ): ?>
								 <button type="button" class="button btn-cart" title="<?php echo $this->__('Add to Cart') ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $store)):?> onclick="setLocationAjax(this,'<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId(); ?>')" <?php else : ?> onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" <?php endif; ?>><span><?php echo $this->__('Add to Cart') ?></span></button>
								<?php else: ?>
								<button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart preview" onclick="setLocation('<?php echo $productUrl; ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
							<?php endif; ?>
						<?php endif; ?>
						<?php if (Mage::helper('itactica_quickview')->isEnabled() && Mage::getStoreConfig('intenso/quickview/list_enable', $store)): ?>
							<a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
						<?php endif; ?>
					</div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    <?php if ($this->getRequest()->isAjax() && Mage::helper('itactica_quickview')->isEnabled()): ?>
    <script type="text/javascript">
        new ProductInfo('.quickview-button', '.product-image', {});
        $j(document).trigger('product-media-loaded');
    </script>
    <?php endif; ?>
<?php if (!$this->getRequest()->isAjax()): ?>
    </ul>
	</div>
	<div id="pager" class="toolbar-bottom">
    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/pager.phtml')->toHtml(); ?>
</div>
</section>
</div>
<?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
	<?php if($this->getCompareId()): ?>
		var compareProducts = Array(0,<?php echo $this->getCompareId(); ?>);for (i = 0; i < compareProducts.length; i++) {if (document.getElementById('compare-id-'+compareProducts[i]) != undefined) document.getElementById('compare-id-'+compareProducts[i]).classList.add('compared');}
	<?php endif; ?>
	<?php if($this->getWhishlistId()): ?>
		var wishlistProducts = Array(0,<?php  echo $this->getWhishlistId(); ?>);for (i = 0; i < wishlistProducts.length; i++) {if (document.getElementById('wishlist-id-'+wishlistProducts[i]) != undefined)document.getElementById('wishlist-id-'+wishlistProducts[i]).classList.add('active');}
		var wishlistThumbProducts = Array(0,<?php  echo $this->getWhishlistId(); ?>);for (i = 0; i < wishlistThumbProducts.length; i++) {if (document.getElementById('wish-id-'+wishlistThumbProducts[i]) != undefined)$('wish-id-'+wishlistThumbProducts[i]).classList.add('active');}
	<?php endif; ?>
		lazyLoad();
		altLazyLoad("img.alt-lazyload");
	setTimeout(function(){
		var layerAnchors = Array.prototype.slice.call(document.querySelectorAll("#layered-navigation  a"),0);
		layerAnchors.forEach(function(anchor){
			var hrefStr = anchor.href;
			var indexOfCatFilter = hrefStr.lastIndexOf("cat");
			var filterHrefStr = hrefStr.substr(indexOfCatFilter+4, hrefStr.length);
			var indexOfCatAfterFilter = filterHrefStr.indexOf('/');

			if(indexOfCatAfterFilter==-1){
				var strToSearch = filterHrefStr.substr(0, filterHrefStr.length);
			}else{
				var strToSearch = filterHrefStr.substr(0, indexOfCatAfterFilter);
			}


			var strToMatch = '/'+strToSearch;
			var strToMatch = new RegExp(strToMatch, 'g');
			var strToMatchCount = (hrefStr.match(strToMatch) || []).length;

			if (strToMatchCount>1) {
				anchor.setAttribute('href', (hrefStr.substr(0, hrefStr.indexOf('filter'))));
			}

			if(hrefStr.indexOf("catalogsearch/result")!==-1){
				hrefStr = hrefStr.replace(/amp;/g,'');
				anchor.setAttribute('href', hrefStr);
			}
		});
	},500);
</script>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
