<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<div id="account-forgotpassword" class="account-forgotpassword">
	<form id="social-forgot-pass" name="social-forgot-pass" method="post" >
	<a class="close-reveal-modal" aria-label="Close">CLOSE</a>
	 <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<h3 class="center account-title"><?php echo $this->__('Retrieve password') ?></h3>
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>    
		<ul class="form-list">
			<li class="row">
				<div class="col-xs-12">
					<div class="input-field input-wrapper">
						<label for="email_address" class="required label-floating"><?php echo $this->__('Email Address') ?></label>
						<input type="email" name="email-forgot" placeholder="<?php echo $this->__('Email') ?>" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email_address" class="input-text required-entry validate-email input-floating" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />									
					</div>
				</div>
			</li>
			<?php echo $this->getChildHtml('form.additional.info'); ?>
		</ul>
		<footer class="bottom_box on_the_sides">
				
				 <button id="socialAjaxForgotPassSubmit" type="button" onclick="socialAjaxForgotPass();"  title="<?php echo $this->__('Submit') ?>" class="btn btn-big"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				
				<p class="back-link"><a id="forgot-arrow-left" class="arrow-left" href="javascript:void(0);"><?php echo $this->__('Back to Login') ?></a></p>
		</footer>
    </form>
</div>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(){
//--- Trigger Register Form Submit Event upon pressing ENTER Key..
jQuery('#social-forgot-pass input').keyup(function (e) {
	
  if (e.which == 13) {
	 
 // setTimeout(function(){
	   jQuery('#socialAjaxForgotPassSubmit').trigger('click');
  // },295);
       //<---- Add this line
  }
});

//<![CDATA[
    var dataForm = new VarienForm('social-forgot-pass', true);
//]]>
});
</script>
