<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Create account form template
 *
 * @var $this Mage_Customer_Block_Form_Register
 */
?>
<div id="account-create" class="account-create" style="display:none">
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form  method="post" name="social-register-form" id="social-register-form">
	<a class="close-reveal-modal" aria-label="Close">CLOSE</a>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="row">
            <div class="col-sm-12 create-account">
                <h3 class="account-title center"><?php echo $this->__('Create a new account ') ?></h3>
					<div class="row">
                    <ul class="form-list">
                         <li class="col-sm-12">
                            <div class="row"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?></div>
                        </li>
                       <li class="col-sm-12">
							<div class="input-field input-wrapper">
								<label for="email_address_register" class="required label-floating"><?php echo $this->__('Email Address') ?></label>
								<input type="email" placeholder="<?php echo $this->__('Email Address') ?>" name="email" id="email_address_register" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text input-floating validate-email required-entry input-floating" />
							</div>
                        </li>
                        <?php if ($this->isNewsletterEnabled()): ?>
                         <li class="col-sm-12">
							<div class="input-box checkbox">
								<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="filled-in" checked="checked" />
								<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
							</div>
                        </li>
                        <?php endif ?>
						<?php /* $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
						<?php if ($_dob->isEnabled()): ?>
							<li class="col-sm-12">
									<?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
							</li>
						<?php endif ?>
						<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
						<?php if ($_taxvat->isEnabled()): ?>
							<li class="col-sm-6">
								<div class="input-field input-wrapper">
									<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
								</div>
							</li>
						<?php endif ?>
						<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
						<?php if ($_gender->isEnabled()): ?>
							<li class="col-sm-6"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
						<?php endif */ ?>
                    </ul>
					</div>
                <?php if($this->getShowAddressFields()): ?>

                    <input type="hidden" name="create_address" value="1" />
                    <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
					<div class="row">
                    <ul class="form-list">
                        <li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="company" class="label-floating"><?php echo $this->__('Company') ?></label>
								<div class="input-box">
									<input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="telephone" class="required label-floating"><?php echo $this->__('Telephone') ?></label>
								<div class="input-box">
									<input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
								</div>
							</div>
                        </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
						<li class="col-sm-12">
							<div class="input-field input-wrapper">
							   <label for="street_1" class="required label-floating"><?php echo $this->__('Address') ?></label>
								<div class="input-box">
									<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text input-floating <?php echo $_streetValidationClass ?>" />
								</div>
							</div>
                        </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
						<li class="col-sm-12">
							<div class="input-field input-wrapper">
								<label for="street_<?php echo $_i ?>" = class="required label-floating <?php echo $_streetValidationClass ?>"><?php echo $this->__('Address 2') ?></label>
								 <div class="input-box">
									<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text input-floating <?php echo $_streetValidationClass ?>" />
								</div>
							</div>
                        </li>
                    <?php endfor; ?>
                        <li class="col-sm-6">
							<div class="input-field input-wrapper">
								  <label for="city" class="required label-floating"><?php echo $this->__('City') ?></label>
								<div class="input-box">
									<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">

                                <div class="input-field input-wrapper">
								<label for="region_id" class="required label-floating"><?php echo $this->__('State/Province') ?></label>
                                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                    //]]>
                                    </script>
                                    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text input-floating validate <?php //echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                            </div>
                        </li>
                       <li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="zip" class="required label-floating"><?php echo $this->__('Zip/Postal Code') ?></label>
								<div class="input-box">
									<input type="number" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text input-floating validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">
                                <div class="input-field input-wrapper">
                                    <?php echo $this->getCountryHtmlSelect() ?>
                                </div>
                            </div>
                        </li>
                    </ul>
					</div>
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
					<div class="row">
						<ul class="form-list">
							<li class="col-sm-6">
                                <div class="input-field input-wrapper">
									<label for="password" class="required label-floating"><?php echo $this->__('Password') ?></label>
									<div class="input-box">
										<input type="password" name="password" placeholder="<?php echo $this->__('Password') ?>" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" class="input-text input-floating required-entry validate-password" />
									</div>
                                </div>
							</li>
							<li class="col-sm-6">
                                <div class="input-field input-wrapper">
									<label for="confirmation" class="required label-floating"><?php echo $this->__('Confirm Password') ?></label>
                                    <div class="input-box">
										<input type="password" name="confirmation" placeholder="<?php echo $this->__('Confirm Password') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text input-floating required-entry validate-cpassword" />
									</div>
                                </div>
							</li>
							<li class="col-sm-12">
								<?php echo $this->getChildHtml('form.additional.info'); ?>
							</li>
							<li class="col-sm-12">
								<ul>
									<?php echo $this->getChildHtml('persistent.remember.me'); ?>
								</ul>
							</li>
                    </ul>
					</div>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <footer class="bottom_box on_the_sides">
                        <button id="socialRegisterSubmit" type="button" onclick="socialAjaxRegister()" title="<?php echo $this->__('Submit') ?>" class="btn btn-big"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </footer>
					 <div class="login_bottom">
						<div class="heading-divider">
						   <h5><?php echo $this->__("Already have an account?") ?></h5>
						</div>
						<button type="button" title="<?php echo $this->__('Sign In') ?>" class="btn btn-big secondary" id="register-arrow-left"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
					 </div>
                </div>
            </div>

    </form>
	</div>
<script>
	document.addEventListener("DOMContentLoaded", function(){
		//--- Trigger Register Form Submit Event upon pressing ENTER Key..
		jQuery('#social-register-form input').keyup(function (e) {
		  if (e.which == 13) {
			jQuery('#socialRegisterSubmit').trigger('click');
			//return false;    //<---- Add this line
		  }
		});
        var dataForm = new VarienForm('social-register-form', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        <?php if($this->getShowAddressFields() && Mage::helper('itactica_intenso')->formFieldsType() == 'mdformfields'): ?>
        jQuery(function() {
            jQuery('#country').on('change keyup', function(event) {
                regionUpdater.update();
            });

            if (canUseChosen()) {
                // fix RegionUpdater for chosen.js
                Object.extend(Validation, {
                    isVisible : function(elm) {
                        while(elm.tagName != 'BODY') {
                            // validate DOB and Region hidden select boxes
                            if (elm.id == 'month' || elm.id == 'day' || elm.id == 'year' || elm.id == 'region_id') {
                                return true;
                            }
                            if(!$(elm).visible()) return false;
                            elm = elm.parentNode;
                        }
                        return true;
                    }
                });
                regionUpdater.update = regionUpdater.update.wrap(function(parentMethod){
                    // parent "update" method call
                    parentMethod();

                    // after "update" method fires
                    regionUpdater.regionSelectEl.hide();
                    regionChosen = jQuery('#region_id_chosen');
                    if(regionUpdater.regionTextEl.visible()) {
                        regionChosen.hide();
                        regionChosen.parent().removeClass('input-box-select');
                        regionChosen.parent().parent().removeClass('select-list');
                    } else {
                        regionChosen.show();
                        regionChosen.parent().addClass('input-box-select');
                        regionChosen.parent().parent().addClass('select-list');
                        jQuery('#region_id').trigger("chosen:updated");
                    }
                });

                jQuery('#region_id').on('change keyup', function(event) {
                    jQuery('#region').val(jQuery(this).children("option").filter(":selected").text());
                });
                regionUpdater.update();

            } else {
                regionUpdater.update = regionUpdater.update.wrap(function(parentMethod){
                    // parent "update" method call
                    parentMethod();

                    // after "update" method fires
                    if(regionUpdater.regionTextEl.visible()) {
                        jQuery('.state-province-field').removeClass('select-list');
                        jQuery('.state-province-field > .input-box').removeClass('input-box-select');
                    } else {
                        jQuery('.state-province-field').addClass('select-list');
                        jQuery('.state-province-field > .input-box').addClass('input-box-select');
                    }
                });
                regionUpdater.update();
            }

            function canUseChosen() {
                if (window.navigator.appName === "Microsoft Internet Explorer") {
                    return document.documentMode >= 8;
                }
                if (/iP(od|hone)/i.test(window.navigator.userAgent)) {
                    return false;
                }
                if (/Android/i.test(window.navigator.userAgent)) {
                    if (/Mobile/i.test(window.navigator.userAgent)) {
                        return false;
                    }
                }
                return true;
            }
        });
        <?php endif; ?>
	});
</script>
