<?php  $defaultCountryCode = Mage::getStoreConfig('general/country/default', Mage::app()->getStore()); ?>
<div class="billing_address">
    <h3 id="billing_step_header" class="step_1"><?php echo($this->__("Billing Address")); ?></h3>
    <?php if ($this->customerHasAddresses()): ?>
	<div class="col-sm-12">
		<p class="label"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></p>
		<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
			
			<label class="chosen-label" for="billing-address-select"><?php echo $this->__('Select a billing address') ?></label>
			<?php echo $this->getAddressesHtmlSelect('billing') ?>
			<input type='hidden' name='islogin2' id='islogin2' value='1'/>
		</div>
	</div>
    <?php endif; ?>
    <fieldset class="group-select"
              id="billing-new-address-form" <?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getBillingAddress()->getId() ?>"
               id="billing:address_id"/>
        <ul>
            <?php $helper = Mage::helper('onestepcheckout') ?>
            <?php $fieldValue = $helper->getFieldValue() ?>
            <?php $fields = $helper->getFieldEnables() ?>
            <?php $checkCountry = 0 ?>
            <?php $checkRegion = 0 ?>
            <?php $row = 0; ?>
            <?php for ($i = 0; $i < 20; $i++): ?>
                <?php if ($fields[$i]['value'] == 'country') $checkCountry = 1 ?>
                <?php if ($fields[$i]['value'] == 'region') $checkRegion = 1 ?>
                <?php if (Mage::getSingleton('customer/session')->isLoggedIn() && $fields[$i]['value'] == 'email') continue; ?>
                <?php if (!$fields[$i]['value'] || $fields[$i]['value'] == '0') continue; ?>
                <?php if (($i % 2 == 0) || (($i % 2 != 0) && (!$fields[$i - 1]['value'] || $fields[$i - 1]['value'] == '0' || (Mage::getSingleton('customer/session')->isLoggedIn() && $fields[$i - 1]['value'] == 'email')))): ?>
                    <li>
                <?php endif ?>
                <?php if ((($i % 2 == 0) && ($fields[$i]['value'] && $fields[$i]['value'] != '0') && (!$fields[$i + 1]['value'] || $fields[$i + 1]['value'] == '0' || (Mage::getSingleton('customer/session')->isLoggedIn() && $fields[$i + 1]['value'] == 'email'))) || (($i % 2 != 0) && ($fields[$i]['value'] && $fields[$i]['value'] != '0') && (!$fields[$i - 1]['value'] || $fields[$i - 1]['value'] == '0' || (Mage::getSingleton('customer/session')->isLoggedIn() && $fields[$i - 1]['value'] == 'email')))):
                ?>
                <div class="one-field">
				
                <?php else: ?>
                <div class="two-fields <?php if ($row % 2 != 0) echo 'last' ?>">
				
                <?php $row++; ?>
            <?php endif ?>
                <?php if (!$fields[$i]['value'] || $fields[$i]['value'] == '0') continue; ?>
                <?php if ($fields[$i]['value'] == 'street'): ?>
				<div class="input-field input-wrapper">
                    <label class="label-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required <?php endif ?>"
                           for="billing:street1"><?php echo $this->__('Address') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
                <input onkeyup="validateElement(this.id)" type="text"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
					   placeholder="<?php echo $this->__('Address') ?>"
                       name="billing[street][]" id="billing:street1"
                       value="<?php echo $this->htmlEscape($this->getBillingAddress()->getStreet(1)) ?>"
                       class="<?php if ($helper->getFieldRequire($fields[$i]['value'])) echo 'required-entry'; ?> input-text input-floating"/>
				</div>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines();
                               $_i <= $_n;
                               $_i++): ?>
				   
			   <div class="input-field input-wrapper">
			    <label class="label-floating" for="billing:street<?php echo $_i ?>">
					<?php echo Mage::helper('core')->quoteEscape($this->__('Address ' . $_i)) ?>
				</label>
                <input onkeyup="validateElement(this.id)" type="text"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address ' . $_i)) ?>"
					   placeholder="<?php echo $this->__('Address '. $_i) ?>"
                       name="billing[street][]" id="billing:street<?php echo $_i ?>"
                       value="<?php echo $this->htmlEscape($this->getBillingAddress()->getStreet($_i)) ?>"
                       class="input-text input-floating"/>
			   </div>
                <?php endfor ?>
				
                <?php elseif ($fields[$i]['value'] == 'country'): ?>
				<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
                    <label class="chosen-label <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required <?php endif ?>"
                           for="billing:country_id"><?php echo $this->__('Country') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
					
                <?php //echo $this->getCountryHtmlSelect('billing') ?>
				<!---------------------------------------------------- ZEE CODE ------------------------------------------------------->
				<!----- To resolve Populating Country List issue --->
				<?php $allowedCountries = explode(',', Mage::getStoreConfig('general/country/allow', Mage::app()->getStore()));
					 $defaultCountry =  Mage::getStoreConfig('onestepcheckout/general/country_id', Mage::app()->getStore());
				?>
				<select name="billing[country_id]" id="billing:country_id" class="validate-select" title="Country" style="width:135px">
					<option></option>
					<?php foreach($allowedCountries as $countryCode){ ?>
						<option <?php if($defaultCountry && $defaultCountry==$countryCode){ echo "selected"; }?> value="<?php echo $countryCode; ?>"><?php echo Mage::app()->getLocale()->getCountryTranslation($countryCode); ?></option>
					<?php }?>
				</select>
				<!---------------------------------------------------- ZEE CODE ------------------------------------------------------->
                <?php if (!$helper->getFieldRequire($fields[$i]['value'])): ?>
                    <script type="text/javascript">
                        if ($('billing:country_id'))
                            $('billing:country_id').removeClassName('validate-select');
                    </script>
                <?php endif ?>
				</div>
                <?php elseif ($fields[$i]['value'] == 'region'): ?>
				<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
                    <label class="chosen-label <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required<?php endif ?>"
                           for="billing:region"><?php echo $this->__('State/Province') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
                    <select id="billing:region_id" name="billing[region_id]"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                            class="<?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "validate-select"; ?>"
                            style="display:none;width:135px;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                <?php if (!$helper->enableGeoip()): ?>
                    <script type="text/javascript">
                        $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->htmlEscape($this->getBillingAddress()->getRegionId()) ?>");
                    </script>
                <?php endif; ?>
                <input onkeyup="validateElement(this.id)" type="text" id="billing:region" name="billing[region]"
                       value="<?php echo $this->htmlEscape($this->getBillingAddress()->getRegion()) ?>"
					   placeholder="<?php echo $this->__('State/Province') ?>"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                       class="input-text input-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])) echo 'required-entry'; ?> "
                       style="display:none"/>
                <?php if (!$helper->getFieldRequire($fields[$i]['value'])): ?>
                    <script type="text/javascript">
                        if ($('billing:region_id'))
                            $('billing:region_id').removeClassName('validate-select');
                    </script>
				</div>
                <?php endif ?>
                <?php elseif ($fields[$i]['value'] == 'prefix'): ?>
                <?php $customerNameBlock = Mage::getBlockSingleton('customer/widget_name') ?>
				
                    <?php if ($customerNameBlock->getPrefixOptions() === false): ?>
					<div class="input-field input-wrapper ">
					<label class="label-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required<?php endif ?>"
                           for="billing:prefix"><?php echo $this->__('Prefix Name') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
					<input onkeyup="validateElement(this.id)" type="text"
                       id="<?php echo $customerNameBlock->getFieldId('prefix') ?>"
					   placeholder="<?php echo $this->__('Prefix Name') ?>"
                       name="billing[<?php echo $customerNameBlock->getFieldName('prefix') ?>]" value=""
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Prefix')) ?>"
                       class="input-text input-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?> />
				   </div>
                <?php else: ?>
					<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
					<label class="chosen-label <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required<?php endif ?>"
                           for="billing:prefix"><?php echo $this->__('Prefix Name') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
                    <select id="<?php echo $customerNameBlock->getFieldId('prefix') ?>"
                            name="billing[<?php echo $customerNameBlock->getFieldName('prefix') ?>]"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Prefix')) ?>"
                            class="<?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?>>
                        <?php foreach ($customerNameBlock->getPrefixOptions() as $_option): ?>
                            <option value="<?php echo $_option ?>"><?php echo $this->__($_option) ?></option>
                        <?php endforeach ?>
                    </select>
					</div>
                <?php endif; ?>
                <?php elseif ($fields[$i]['value'] == 'suffix'): ?>
                <?php $customerNameBlock = Mage::getBlockSingleton('customer/widget_name') ?>
                   
                    <?php if ($customerNameBlock->getSuffixOptions() === false): ?>
					<div class="input-field input-wrapper">
					 <label class="label-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required <?php endif ?>"
                           for="billing:prefix"><?php echo $this->__('Suffix Name') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
					<input onkeyup="validateElement(this.id)" type="text"
                       id="<?php echo $customerNameBlock->getFieldId('suffix') ?>"
					   placeholder="<?php echo $this->__('Suffix Name') ?>"
                       name="billing[<?php echo $customerNameBlock->getFieldName('suffix') ?>]" value=""
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Suffix')) ?>"
                       class="input-text input-floating <?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?> />
					   </div>
                <?php else: ?>
				<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
					<label class="chosen-label <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required <?php endif ?>"
                           for="billing:prefix"><?php echo $this->__('Suffix Name') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label><!--<br/>-->
                    <select id="<?php echo $customerNameBlock->getFieldId('suffix') ?>"
                            name="billing[<?php echo $customerNameBlock->getFieldName('suffix') ?>]"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Suffix')) ?>"
                            class="<?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "required-entry"; ?>" <?php echo $customerNameBlock->getFieldParams() ?>>
                        <?php foreach ($customerNameBlock->getSuffixOptions() as $_option): ?>
                            <option value="<?php echo $_option ?>"><?php echo $this->__($_option) ?></option>
                        <?php endforeach ?>
                    </select>
				</div>
                <?php endif; ?>
                <?php elseif ($fields[$i]['value'] == 'birthday'): ?>
                    <?php $_dob = $this->getLayout()->createBlock('onestepcheckout/widget_dob') ?>
                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                <?php elseif ($fields[$i]['value'] == 'gender'): ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
					<div class="input-field input-wrapper select-wrapper chosen-wrapper ">
                    <label class="chosen-label <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>required <?php endif ?>"
                           for="<?php echo $_gender->getFieldId('gender') ?>"><?php echo $this->__('Gender') ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value'])): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label>
					<!--<br/>-->
                    <select id="<?php echo $_gender->getFieldId('gender') ?>"
                            name="billing[<?php echo $_gender->getFieldName('gender') ?>]"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Gender')) ?>"
                            class="<?php if ($helper->getFieldRequire($fields[$i]['value'])) echo "validate-select"; ?>" <?php echo $_gender->getFieldParams() ?>>
                        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions(); ?>
                        <?php $value = $_gender->getGender(); ?>
                        <?php foreach ($options as $option): ?>
                            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value || $option['value'] == $this->getCustomerData($_gender->getFieldName('gender'))) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
					</div>
                <?php else: ?>
				<div class="input-field input-wrapper">
                    <label class=" label-floating
                        <?php if ($helper->getFieldRequire($fields[$i]['value']) || $fields[$i]['value'] == 'firstname' || $fields[$i]['value'] == 'lastname' || $fields[$i]['value'] == 'email'): ?>required <?php endif ?>"
                        for="billing:<?php echo $fields[$i]['value']; ?>"><?php echo $this->__($fieldValue[$fields[$i]['value']]) ?>
                        <?php if ($helper->getFieldRequire($fields[$i]['value']) || $fields[$i]['value'] == 'firstname' || $fields[$i]['value'] == 'lastname' || $fields[$i]['value'] == 'email'): ?>
                            <em>*</em>
                        <?php endif ?>
                    </label>
					<!--<br/>-->
					<?php //--- ZEE CODE --- If field type is telephone...
					if( $fields[$i]['value'] == "telephone"){ ?>
					<input type="hidden" name="billing[<?php echo $fields[$i]['value']; ?>]" id="billing:<?php echo $fields[$i]['value']; ?>_original">
					<input onkeyup="validateElement(this.id)" type="tel" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__($fieldValue[$fields[$i]['value']])) ?>" id="billing:<?php echo $fields[$i]['value']; ?>"
                       autocomplete="<?php if ($fields[$i]['value'] == 'email') echo 'off'; ?>"
                       onkeypress="return isTelephoneKey(event)"
                       name="billing[<?php echo $fields[$i]['value']; ?>]"
                       value="<?php echo $this->htmlEscape($this->getCustomerData($fields[$i]['value'])) ?>"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__($fieldValue[$fields[$i]['value']])) ?>"
                       class="input-text validate-phone-billing input-floating input-floating required-entry"/>
					
					
					<?php }else{?>
					<input onkeyup="validateElement(this.id)" <?php if($fields[$i]['value'] == 'fax' || $fields[$i]['value'] == 'telephone'):?> type="tel" <?php else: ?> type="text" <?php endif; ?> placeholder="<?php echo $this->__($fieldValue[$fields[$i]['value']]) ?>" id="billing:<?php echo $fields[$i]['value']; ?>"
                       autocomplete="<?php if ($fields[$i]['value'] == 'email') echo 'off'; ?>"
                       name="billing[<?php echo $fields[$i]['value']; ?>]"
                       value="<?php echo $this->htmlEscape($this->getCustomerData($fields[$i]['value'])) ?>"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__($fieldValue[$fields[$i]['value']])) ?>"
                       class="input-text input-floating input-floating <?php if ($helper->getFieldRequire($fields[$i]['value']) || $fields[$i]['value'] == 'firstname' || $fields[$i]['value'] == 'lastname' || $fields[$i]['value'] == 'email') echo 'required-entry'; ?>"/>
					<?php } ?>
                    <?php if ($helper->enableGeoip()): ?>
                    <?php if (($fields[$i]['value'] == 'postcode') && $helper->allowDetectByPostcode()): ?>
                    <span id="billing_<?php echo $fields[$i]['value'] ?>_autocomplete_indicator"
                          class="autocomplete-indicator" style="display:none;">
                                            <img class="v-middle" alt="Loading..."
                                                 src="<?php echo $this->getSkinUrl('images/geoip/indicator.gif') ?>">
                                        </span>
									
                    <div id="billing:<?php echo $fields[$i]['value'] . '_autocomplete'; ?>" class="autocomplete"
                         style="display:none; position:absolute; background-color:#FFFFFF; max-height:230px; overflow:auto; border:1px solid #B6B6B6"></div>
						 
                <?php endif; ?>
                    <?php if (($fields[$i]['value'] == 'city') && $helper->allowDetectByCity()): ?>
                    <span id="billing_<?php echo $fields[$i]['value'] ?>_autocomplete_indicator"
                          class="autocomplete-indicator" style="display:none;">
                                            <img class="v-middle" alt="Loading..."
                                                 src="<?php echo $this->getSkinUrl('images/geoip/indicator.gif') ?>">
                                        </span>
                    <div id="billing:<?php echo $fields[$i]['value'] . '_autocomplete'; ?>" class="autocomplete"
                         style="display:none; position:absolute; background-color:#FFFFFF; max-height:230px; overflow:auto; border:1px solid #B6B6B6"></div>
                <?php endif; ?>
                <?php endif; ?>
                    <?php if ($fields[$i]['value'] == 'email'): ?>
                    <span id="valid_email_address_image" style="display:none;"><img
                                src="<?php echo $this->getSkinUrl('images/onestepcheckout/flatnew/valid.gif') ?>"
                                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Valid Email Address')); ?>"
                                alt="<?php echo $this->__('Valid Email Address'); ?>" width="18"/></span>
                    <div id="email-error-message" class="error-message"></div>
                    <div id="email-info-message" class="info-message"></div>
                <?php endif ?>
				</div>
                <?php endif ?>
				</div>
                <?php if (($i % 2 != 0) || (($i % 2 == 0) && (!$fields[$i + 1]['value'] || $fields[$i + 1]['value'] == '0' || (Mage::getSingleton('customer/session')->isLoggedIn() && $fields[$i + 1]['value'] == 'email')))): ?>
                    </li>
                <?php endif ?>
            <?php endfor ?>
            <?php if ($checkCountry == 0): ?>
                <div style="display:none;">
                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div>
            <?php endif ?>
            <?php if (!$this->isCustomerLoggedIn() && Mage::helper('onestepcheckout')->enableRegistration() && Mage::helper('onestepcheckout')->allowGuestCheckout() && !$this->getRequest()->getParams('register')): ?>
                <li class="create_account">
                    <div>
                        <input id="create_account_checkbox_id" type="checkbox" name="create_account_checkbox"
                               value="1"/>
                        <label for="create_account_checkbox_id"><?php echo $this->__('Create an account for later use') ?></label>
                    </div>
                </li>
                <script type="text/javascript">
                    Event.observe('create_account_checkbox_id', 'click', function () {
                        if ($('create_account_checkbox_id').checked)
                            $('password_section_id').show();
                        else
                            $('password_section_id').hide();
                    });
                </script>
            <?php endif; ?>
            <?php if (!$this->isCustomerLoggedIn() && (Mage::helper('onestepcheckout')->enableRegistration() || !Mage::helper('onestepcheckout')->allowGuestCheckout())): ?>
                <li id="password_section_id"
                    <?php if (!Mage::helper('onestepcheckout')->allowGuestCheckout() || $this->getRequest()->getParams('register')): ?>style="display:block"
                    <?php else: ?>style="display:none"<?php endif ?>>
					<!-- Password -->
                    <div class="two-fields">
						<div class="input-field input-wrapper">
							<label class="required label-floating" for="billing:customer_password"><?php echo $this->__('Password') ?> <em>*</em></label>
						<!--<br/>-->
							<input type="password" name="billing[customer_password]" id="billing:customer_password" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>"
								   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>"
								   class="input-text input-floating required-entry validate-password"/>
						</div>
                    </div>
					<!-- Confirm Password -->
                    <div class="two-fields last">
						<div class="input-field input-wrapper">
							<label class="required label-floating"  for="billing:confirm_password"><?php echo $this->__('Confirm Password') ?> <em>*</em></label>
							<!--<br/>-->
							<input onkeyup="validateElement(this.id)" type="password" name="billing[confirm_password]" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="billing:confirm_password" class="input-text input-floating required-entry validate-cpassword" />
						</div>
                    </div>
                </li>
            <?php endif ?>
            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                <li class="control shipping_other_address">
                    <input type="checkbox" name="billing[save_in_address_book]" value="1"
                           title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book"
                           onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getBillingAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
                           class="checkbox"/><label
                            for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </li>
            <?php else: ?>
                <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1"/></li>
            <?php endif; ?>
            <li style="display:none;">
                <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="1"/>
            </li>

            <?php if ($this->isCustomerLoggedIn()): ?>
                <li style="margin-top: 0;"><input type='hidden' name='islogin' id='islogin' value='1'/></li>
            <?php endif; ?>
            <li style="margin-top: 0;"><input type='hidden' name='emailvalid' id='emailvalid' value=''/></li>

        </ul>
    </fieldset>
    <?php if ($this->isShowShippingAddress()): ?>
        <ul>
            <li class="shipping_other_address">
                <div class="input-box input-different-shipping">
                    <input onclick="showDifferentAdress();" type="checkbox" name="shipping[different_shipping]"
                           id="shipping:different_shipping"
                           value="1" <?php if (Mage::getSingleton('checkout/session')->getData('different_shipping')) echo 'checked'; ?> />
                    <label for="shipping:different_shipping"><?php echo $this->__('Ship to different address'); ?></label>
                </div>
            </li>
        </ul>
    <?php else: ?>
        <!--<li>
                        <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="1" />
        </li>-->
    <?php endif; ?>
    <script type="text/javascript">var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
    <script type="text/javascript">
        //<![CDATA[

        if ($('billing:region') || $('billing:region_id'))
            var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions);

        <?php if (!$helper->getFieldRequire('region')): ?>
        if ($('billing:region_id')) {
            $('billing:region_id').removeClassName('validate-select');
            $('billing:region_id').removeClassName('required-entry');
        }
        <?php endif ?>
        if ($('billing:email')) {
            Event.observe(document, "dom:loaded", function () {
                var url = '<?php echo $this->getUrl('onestepcheckout/index/is_valid_email', array('_secure' => true)) ?>';
                var email_address = $('billing:email').value;
                if(email_address) {
                    var parameters = {email_address: email_address};
                    var request = new Ajax.Request(
                        url,
                        {
                            parameters: parameters,
                            onComplete: check_valid_email.bindAsEventListener($('billing:email')),
                            onFailure: ''
                        });
                }
            });
            Event.observe('billing:email', 'change', function () {
                var url = '<?php echo $this->getUrl('onestepcheckout/index/is_valid_email', array('_secure' => true)) ?>';
                var email_address = $('billing:email').value;
                var parameters = {email_address: email_address};
                var request = new Ajax.Request(
                    url,
                    {
                        parameters: parameters,
                        onComplete: check_valid_email.bindAsEventListener(this),
                        onFailure: ''
                    });
            });
        }
        if ($('billing-address-select')) {
            Event.observe('billing-address-select', 'change', function () {
                var isNew = $('billing-address-select').value ? false : true;
                setNewAddress(isNew, 'billing', save_address_url, update_address_shipping, update_address_payment, update_address_review);
            });
        }
		//console.log(jQuery('label[for="billing:region"]'));
		// if ($('billing:region_id')){
			 // $("label[for*='billing:region']").addClassName("chosen-label");
			 // $("label[for*='billing:region']").removeClassName("label-floating");
			
		// }
		// else{
			 // $("label[for*='billing:region']").removeClassName("chosen-label");
			 // $("label[for*='billing:region']").addClassName("label-floating");
		// }
        //]]>
    </script>


    <script type="text/javascript">
        <?php if ($helper->enableGeoip()): ?>
        /*
         Show list postcode billing
         */
        <?php if ($helper->allowDetectByPostcode()): ?>
        new Ajax.Autocompleter(
            'billing:postcode',
            'billing:postcode_autocomplete',
            '<?php echo $this->getUrl('onestepcheckout/geoip/checkPostcode') ?>',
            {
                paramName: 'postcode',
                minChars:<?php echo $helper->getMinCharsPostcode() ?>,
                indicator: 'billing_postcode_autocomplete_indicator',
                updateElement: fillFilterBilling,
                evalJSON: 'force'
            }
        );
        <?php endif; ?>

        /*
         Show list city billing
         */
        <?php if ($helper->allowDetectByCity()): ?>
        new Ajax.Autocompleter(
            'billing:city',
            'billing:city_autocomplete',
            '<?php echo $this->getUrl('onestepcheckout/geoip/checkCity') ?>',
            {
                paramName: 'city',
                minChars:<?php echo $helper->getMinCharsCity() ?>,
                indicator: 'billing_city_autocomplete_indicator',
                updateElement: fillFilterBilling,
                evalJSON: 'force'
            }
        );
        <?php endif; ?>

        function fillFilterBilling(li) {
            var country = li.getAttribute('country');
            var region = li.getAttribute('region');
            var region_id = li.getAttribute('region_id');
            var city = li.getAttribute('city');
            var postcode = li.getAttribute('postcode');
            if (city != '') {
                if ($('billing:postcode')) {
                    $('billing:postcode').value = postcode;
                }
            }
            if (country != '') {
                if ($('billing:country_id')) {
                    $('billing:country_id').value = country;
                }
            }
            if (region != '') {
                if ($('billing:region')) {
                    $('billing:region').value = region;
                }
            }

            if (region_id != '') {
                if ($('billing:region_id')) {
                    $('billing:region_id').value = region_id;
                }
            }

            if (city != '') {
                if ($('billing:city')) {
                    $('billing:city').value = city;
                }
            }

            updateBillingRegion();

        }
        <?php endif; ?>
        function updateBillingRegion() {
            var countryEl = $('billing:country_id');
            var regionTextEl = $('billing:region');
            var regionSelectEl = $('billing:region_id');
            var regions = <?php echo $this->helper('directory')->getRegionJson() ?>;
            var config = regions['config'];
            delete regions.config;
            var regions = regions;
            var zipEl = $(zipEl);
            disableAction = (typeof disableAction == 'undefined') ? 'hide' : disableAction;

            updateRegion(countryEl, regionTextEl, regionSelectEl, regions, disableAction, zipEl);
        }
        updateBillingRegion();
    </script>

    <?php if (Mage::getStoreConfig('onestepcheckout/general/suggest_address', Mage::app()->getStore()->getStoreId())): ?>
        <script type="text/javascript">
            var autocompleteBilling;
            //Huy - change from sublocality => sublocality_level_1
            var componentBillingForm = {
                subpremise: 'short_name',
                street_number: 'short_name',
                route: 'long_name',
                locality: 'long_name',
                administrative_area_level_1: 'short_name',
                administrative_area_level_2: 'short_name',
                country: 'short_name',
                postal_code: 'short_name',
                sublocality_level_1: 'long_name'
            };

            autocompleteBilling = new google.maps.places.Autocomplete(
                (document.getElementById('billing:street1')),
                {types: ['geocode']});

            google.maps.event.addListener(autocompleteBilling, 'place_changed', function () {
                fillBillingAddress();
            });

            function fillBillingAddress() {
                var place = autocompleteBilling.getPlace();
                var street, city, region_id, region, country, postal_code, sublocality;

                for (var i = 0; i < place.address_components.length; i++) {
                    var addressType = place.address_components[i].types[0];
                    if (componentBillingForm[addressType]) {
                        if (addressType == 'subpremise') {
                            street = place.address_components[i]['long_name'];
                        }
                        if (addressType == 'street_number') {
                            if (street)
                                street = street + '/' + place.address_components[i]['long_name'];
                            else
                                street = place.address_components[i]['long_name'];
                        }
                        if (addressType == 'route') {
                            if (street)
                                street += ' ' + place.address_components[i][componentBillingForm['route']];
                            else
                                street = place.address_components[i][componentBillingForm['route']];
                        }
                        if (addressType == 'locality')
                            city = place.address_components[i][componentBillingForm['locality']];
                        if (addressType == 'administrative_area_level_1') {
                            region_id = place.address_components[i]['short_name'];
                            region = place.address_components[i]['long_name'];
                        }
                        if (addressType == 'country')
                            country = place.address_components[i][componentBillingForm['country']];
                        if (addressType == 'postal_code')
                            postal_code = place.address_components[i][componentBillingForm['postal_code']];
                        //Huy - change from sublocality => sublocality_level_1
                        if (addressType == 'sublocality_level_1')
                            sublocality = place.address_components[i][componentBillingForm['sublocality_level_1']];
                    }
                }
                fillAddress('billing', street, city, region_id, region, country, postal_code, sublocality);
            }
        </script>
    <?php endif; ?>
</div>
<script type="text/javascript">
	var inputBilling = document.getElementById("billing:telephone"),
	cellInputBilling = window.intlTelInput(inputBilling, {
	  geoIpLookup: function(callback) {
		  var countryCode = '<?php echo $defaultCountryCode; ?>';
		  callback(countryCode);
	  },
	  initialCountry: "auto",
	  nationalMode: false,
      autoPlaceholder: 'aggressive',
	  placeholderNumberType: "MOBILE",
	  preferredCountries: ['us', 'ae', 'pk'],
	  utilsScript: "<?php echo $this->getSkinUrl('phone-validation/js/utils.js'); ?>"
	});
	
	inputBilling.parentElement.parentElement.className += " mobile-floating";
	

	
	inputBilling.addEventListener('countrychange', function(e) {
		var advice = document.getElementById('advice-validate-phone-billing-billing:telephone');
		if(inputBilling.placeholder && advice){
			advice.innerText = 'Please enter a valid Mobile No eg.'+inputBilling.placeholder;
		}
		cellInputValidation(inputBilling.placeholder);		
	});
	
	cellInputBilling.promise.then(function() {
		cellInputValidation(inputBilling.placeholder);
	});
	
	
	function cellInputValidation(inputPlaceholder){
		Validation.add('validate-phone-billing', 'Please enter a valid Mobile No eg.'+inputPlaceholder, function(v) {
			return (!Validation.get('IsEmpty').test(v) && cellInputBilling.isValidNumber() && (/[0-9-()+]{3,20}$/).test(inputBilling.value))
		});
	}

    inputBilling.addEventListener('change', function(e) {
		if(inputBilling.value){
			var dialCode = cellInputBilling.selectedCountryData.dialCode;
			var str = inputBilling.value;
			var re = new RegExp("^[+]" + dialCode,"i");
			var result = re.test(str);
			var zero = new RegExp("^0+","i");
			zero = zero.test(str);
			var rDialCode = new RegExp("^"+dialCode+"+","i");
			rDialCode = rDialCode.test(str);
			if(typeof dialCode !== "undefined" && result){
				if(result) {
					var pattern = new RegExp("^[+]" + dialCode + "0+","i");
					var result = pattern.test(str);
					if(result){
						inputBilling.value = "+" + dialCode + str.replace(pattern, "");
					}
				} 
			} else if(zero && !cellInputBilling.isValidNumber()) {
				inputBilling.value = "+" + dialCode + parseInt(str, 10);
			} else if(rDialCode && !cellInputBilling.isValidNumber()) {
				inputBilling.value = "+" + str;
			} else {
				if(typeof window.intlTelInputUtils !== "undefined"){
					if(window.intlTelInputUtils.isValidNumber(inputBilling.value, cellInputBilling.selectedCountryData.iso2)){
						inputBilling.value  = "+" + dialCode + inputBilling.value;
					}
				}
			}
            var reDial = str.replace(re);
			if(window.intlTelInputUtils.isValidNumber(reDial,"")){
				inputBilling.value = reDial;
			}
			validateElement(this.id);
            inputBilling.value  = inputBilling.value.split(" ").join("");
		}
	});
	inputBilling.addEventListener('focus', function(e) {
		if(!inputBilling.value){
			inputBilling.value = "+" + cellInputBilling.selectedCountryData.dialCode;
		}
	});

    var handleChange = function() {
		var telephone = document.getElementById('billing:telephone');
		if(telephone){
			telephone.value = telephone.value.split(" ").join("");
		}
	};

    var isTelephoneKey = function(evt) {
		 var charCode = (evt.which) ? evt.which : event.keyCode;
		 console.log(charCode);
		 if(charCode == 43) return true;
		 else if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		 return true;
	}

</script>