<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
//=================================== 3SD CODE ========================================//

	if($this->getProduct()->getTypeId() == "configurable"){
		$simpleProduct =  $_item->getOptionByCode('simple_product')->getProduct();
		$simpleProductId = $simpleProduct->getId();
		$_product = Mage::getSingleton('catalog/product')->load($simpleProductId) ;
	
	} else {
		$_product= Mage::getSingleton('catalog/product')->load($_item->getProductId()) ;	
	}
		
	//--- Get Product Thumbnail Image...
	$thumbnailImage = Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(68, 68)->setWatermarkSize('30x10');
		
	if(Mage::getStoreConfig('checkout/cart/configurable_product_image' , $code) == 'parent'){
		$thumbnailImage = $this->getProductThumbnail()->resize(68, 68)->setWatermarkSize('30x10');
	}
		
	//--- Get Product MAX Quantity from Admin...
	$maxQty = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getMaxSaleQty();

	//=================================== 3SD CODE ========================================//
?>
<li class="item clearfix">
    <?php if ($this->hasProductUrl()): ?>
        <a class="item-image" title="<?php echo $this->escapeHtml($_product->getName()) ?>" href="<?php echo $this->getProductUrl()?>">
			<img src="<?php echo $thumbnailImage; ?>" width="68" height="68" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
        </a>
    <?php else: ?>
        <span class="item-image"><img src="<?php echo $thumbnailImage; ?>" width="68" height="68" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" /></span>
    <?php endif; ?>
    <div class="item-details">
        <p class="item-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->escapeHtml($_product->getName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
       
        <?php /* if (count($_options) > 2): ?>
            <span class="view-more-attr"><?php echo $this->__('Show more details'); ?></span>
        <?php endif; */ ?>
		        <a href="javascript:void(0)" class="btn-remove icon-close" onclick="deleteAction(this,'<?php echo $this->getDeleteUrl() ?>');" title="Remove This Item"><span class="hide"><?php echo $this->__('Remove this Item'); ?></span></a>
   
    <div class="item-price"> 
        <?php if (isset($canApplyMsrp) && $canApplyMsrp): ?>
            <p class="mrsp"><span class="price" title="<?php echo $this->__('See price before order confirmation.'); ?>"><?php echo $this->__('Price'); ?> [?]</span></p>
        <?php else: ?>
            <?php $_productFinalPrice = Mage::getModel('catalog/product')->load($_product->getId())->getFinalPrice(); ?>
			<span class="price"><?php echo $this->helper('checkout')->formatPrice($_productFinalPrice); ?></span>
        <?php endif; //Can apply MSRP ?>
		 <?php if ($isVisibleProduct): ?>
         <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Edit item')) ?>" class="btn-edit">
            <?php echo $this->__('Edit item')?>
        </a>
		  <?php endif ?>
<?php if($controllerName == 'cart' && $actionName == 'index'){ ?>
<?php } else { ?>
 <div data-title="Quantity" class="qty-wrapper product_center" >
	<?php $cartUpdateUrl = $this->getUrl('checkout/cart/ajaxUpdate');?>
    	<div class="qty min clearfix">
            <button type="button" <?php // echo $this->getQty()==1?'disabled "':''; ?> id="<?php echo $_item->getId() ?>_mini_minus" onclick='setTimeout(function(){productAddToCartFormSidebar.submit(this, "<?php echo $cartUpdateUrl?>", "<?php echo $_item->getId() ?>_mini_qty", "<?php echo $_item->getId() ?>", "mini_minus")}, 5)' class="theme_button <?php echo $this->getQty()==1?'icons-trash-empty':''; ?>"><?php echo $this->getQty()==1?'':'-'; ?></button>
			<input autocomplete="off" type="text" oninput="checkInputToUpdate(<?php echo $this->getQty() ?>, this.value, '<?php echo $_item->getId() ?>_mini_update', '<?php echo $_item->getId() ?>', <?php echo $maxQty;?>)"  id="<?php echo $_item->getId() ?>_mini_qty" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>"  title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="3" />
			<button  type="button" id="<?php echo $_item->getId() ?>_mini_plus" onclick='setTimeout(function(){productAddToCartFormSidebar.submit(this, "<?php echo $cartUpdateUrl?>", "<?php echo $_item->getId() ?>_mini_qty", "<?php echo $_item->getId() ?>", "mini_plus")},5)' class="theme_button">+</button>
			
		</div>
		
		<div class="cart-btn-update">
			<button class="btn btn-big small cart-btn-single-row" style="display:none;" onclick='productAddToCartFormSidebar.submit(this, "<?php echo $cartUpdateUrl?>", "<?php echo $_item->getId() ?>_mini_qty", "<?php echo $_item->getId() ?>", null)' type="button" id="<?php echo $_item->getId() ?>_mini_update">Update</button>
		</div>

		<?php //echo 'Max Qty ',$MaxQty ;?>
		<?php if ($isVisibleProduct): ?> 
                <!-- <button type="button" class="edit-qty" onclick='productAddToCartForm.submit(this, "<?php echo $cartUpdateUrl?>")' title="<?php echo $this->__('Edit item parameters') ?>"><i class="icon-pencil"></i></button>-->
            <?php endif ?>
      
    </div>
 
    <script>

	/***================================= ZEE CODE =========================********/
		function checkInputToUpdate(qty, userQty, updateButtonId , pId, maxQty){
			//--- Check and show Update button and Enable Plus if user enetered value is less than max quantity...
			if(qty !=userQty && (qty !="" && userQty != "")){
				jQuery('#'+updateButtonId).show();
			}
			else{
				jQuery('#'+updateButtonId).hide();
			}
		}
		
	jQuery(document).ready(function(){
		//--- Restore the quantity value if clicked anywhere on Body and Hide the Update button
		jQuery(document).click(function(e){
			//--- Check if the Element exists first (if hasnt been deleted from the cart through AJAX call)
			if(jQuery(document).find('<?php echo "#".$_item->getId() ?>_mini_minus').length>0){
				jQuery('#<?php echo $_item->getId() ?>_mini_qty').val('<?php echo $this->getQty(); ?>');
				jQuery('.btn_update_cart_row').hide(); 
				jQuery('.cart-btn-single-row').hide();
			}			
		});
		
		//--- Stop button from disppearing on clicking quantity box, we are hiding it above upon clicking else where ...
		jQuery('.qty ').click(function(event){
		   event.stopPropagation();
		});
		//--- Stop button from disppearing on clicking itself, we are hiding it above upon clicking else where ...
		jQuery('.cart-btn-single-row').click(function(event){
		   event.stopPropagation();
		});
		
		//--- Do not accept any input but for numeric(integers) only....
		jQuery('#<?php echo $_item->getId() ?>_mini_qty').bind('keydown tap touchstart', function (event) {
			var kC = event.keyCode;
			//--- if input was not integer...
			if(  !((kC >= 48 && kC <= 57) || (kC >= 96 && kC <= 105) || kC == 8 || kC==16)) return false;
			//--- if special character was entered while shift key is pressed..
			if(event.shiftKey == true ){
				event.preventDefault();
			}
		});	
	});			
	/***================================= END ZEE CODE =========================********/
</script>
		<?php } ?>
 </div>
	
    </div>
 <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
        <?php endforeach; ?>
	<?php endif; ?>
     
</li>
