<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
	 //var_dump($_helper);
    $_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
    $_categoryBlock = Mage::getSingleton('Mage_Catalog_Block_Category_View');
    $_isRssCatalogEnable = Mage::getStoreConfig('rss/catalog/category');
    $_isSearchResults = false;
    $_isCMSPage = Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms';
    // if current page is search result show search term as title instead of category name
    $pathInfo = Mage::helper('core/url')->getCurrentUrl();
    $pageTitle = $_helper->categoryAttribute($_category, $_category->getName(), 'name');
    //echo "dddddddddd".$_category;
	if (stripos($pathInfo, '/catalogsearch/result') !== false) {
        $pageTitle = Mage::helper('catalogsearch')->getQueryText();
        $_isSearchResults = true;
    }
    if (stripos($pathInfo, '/catalogsearch/advanced/result') !== false) {
        $pageTitle = $this->__('Search results');
        $_isSearchResults = true;
    }

    // if current page is a CMS page remove the title
    if ($_isCMSPage) {
        $pageTitle = '&nbsp;';
    }
?>

<?php $headingTitle = Mage::getStoreConfig('design/product_meta/category_h1_title', Mage::app()->getStore()->getId()); ?>

<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">




<div class="row">
	 <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" itemscope itemtype="http://schema.org/Enumeration">
     <?php if($_category->getCollectionType() == 1 || $_category->getCollectionType() == null): ?>
   <h1 id="category-name" class="truncate" itemprop="name">
     <?php echo $pageTitle ?>
     <?php echo $headingTitle != "" && $_category->getCollectionType() == null  ? "<span class='hide'>".$headingTitle."</span>":""; ?>
     <?php if($_isRssCatalogEnable && !$_isSearchResults && $_categoryBlock->IsTopCategory()): ?>
       <a href="<?php echo $_categoryBlock->getRssLink() ?>" class="link-rss icon-feed" title="<?php echo $this->__('Subscribe to RSS Feed') ?>"><span class="a11y"><?php echo $this->__('Subscribe to RSS Feed') ?></span></a>
     <?php endif; ?>
   </h1>
 <?php else: ?>
   <h3 id="category-name" class="truncate" itemprop="name">
     <?php echo $pageTitle ?>
     <?php if($_isRssCatalogEnable && !$_isSearchResults && $_categoryBlock->IsTopCategory()): ?>
       <a href="<?php echo $_categoryBlock->getRssLink() ?>" class="link-rss icon-feed" title="<?php echo $this->__('Subscribe to RSS Feed') ?>"><span class="a11y"><?php echo $this->__('Subscribe to RSS Feed') ?></span></a>
     <?php endif; ?>
   </h3>
 <?php endif; ?>
		<?php if ($_category->getName() ): ?>
        <p id="amount" class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>
        <?php endif; ?>
		<?php
		 if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image hide"><img itemprop="image" src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }?>
	<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
	<?php endif; ?>
    </div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
	   <div class="actions pull-right">
        <?php if (!$_isCMSPage): ?>
		<!-- ZEE CODE (remove intenso class left-off-canvas-toggle and add class show-left-menu)-->
        <div class="actions-filter"><a class="button show-left-menu  filter-toggle"><?php echo $this->__('Filter'); ?></a></div>

        <?php endif; ?>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <ul class="button-group">
                <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <li><a href="#" class="button icon-<?php echo strtolower($_code); ?> toggle-<?php echo strtolower($_code); ?> <?php if($this->isModeActive($_code)): ?>active<?php endif; ?>" title="<?php echo $_label ?>"><span class="a11y"><?php echo $_label ?></span></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        <?php endif; ?>
    </div>
	</div>
	</div>
	<div class="row">
	  <div class="col-sm-12">
        <?php if (!$_isCMSPage ): ?>
		<?php if (!$_category->getName() ): ?>
        <p id="amount" class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </p>
        <?php endif; ?>
		<?php endif; ?>
    </div>
	</div>

  	</div>

<?php endif ?>
