<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php $_product = $this->getProduct(); ?>
<button type="button" onclick="window.location.href='<?php echo Mage::getUrl().$_product->getUrlKey(); ?>'" title="<?php echo $this->__('Product Detail') ?>" class="btn secondary preview"><?php echo $this->__('Product Detail') ?></button>