<?php
/**
 * Tejar is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<div class="tejar-socialconnect-login">
        <!--<div class="<?php // echo $this->_getColSet(); ?> tejar-socialconnect-login-upper">
            <?php /* if($this->_googleEnabled()): ?>
            <div class="<?php echo $this->_getDescCol(); ?> new-users tejar-socialconnect-login-upper-google">
                <div class="content">
                    <h2><?php echo $this->__('Google Connect'); ?></h2>
                    <p><?php echo $this->__('You can login using your Google account.'); ?></p>
                </div>
            </div>
            <?php endif; ?>
            <?php  if($this->_facebookEnabled()): ?>
            <div class="<?php echo $this->_getDescCol(); ?> new-users tejar-socialconnect-login-upper-facebook">
                <div class="content">
                    <h2><?php echo $this->__('Facebook Connect'); ?></h2>
                    <p><?php echo $this->__('You can login using your Facebook account.'); ?></p>
                </div>
            </div>
            <?php endif; ?>
            <?php if($this->_twitterEnabled()): ?>
            <div class="<?php echo $this->_getDescCol(); ?> new-users tejar-socialconnect-login-upper-twitter">
                <div class="content">
                    <h2><?php echo $this->__('Twitter Connect'); ?></h2>
                    <p><?php echo $this->__('You can login using your Twitter account.'); ?></p>
                </div>
            </div>
            <?php endif; ?>
            <?php if($this->_linkedinEnabled()): ?>
            <div class="<?php echo $this->_getDescCol(); ?> new-users tejar-socialconnect-login-upper-linkedin">
                <div class="content">
                    <h2><?php echo $this->__('LinkedIn Connect'); ?></h2>
                    <p><?php echo $this->__('You can login using your LinkedIn account.'); ?></p>
                </div>
            </div>
            <?php endif;*/ ?>            
        </div>-->
		<div class="login_bottom">
					<div class="heading-divider">
					<h5><?php echo $this->__('Or log in with') ?></h5>
					</div>
		</div>
        <div class="<?php //echo $this->_getColSet(); ?>  tejar-socialconnect-login-lower">
            <?php if($this->_googleEnabled()): ?>
            <div class="<?php echo $this->_getButtCol(); ?> tejar-socialconnect-login-lower-google">
                
                    <?php echo $this->getChildHtml('tejar_socialconnect_google_login_button'); ?>
                
            </div>
            <?php endif; ?>
            <?php if($this->_facebookEnabled()): ?>
            <div class="<?php //echo $this->_getButtCol(); ?> tejar-socialconnect-login-lower-facebook">
                
                    <?php echo $this->getChildHtml('tejar_socialconnect_facebook_login_button'); ?>
                
            </div>
            <?php endif; ?>
            <?php if($this->_twitterEnabled()): ?>
            <div class="<?php //echo $this->_getButtCol(); ?>  tejar-socialconnect-login-lower-twitter">
                
                    <?php echo $this->getChildHtml('tejar_socialconnect_twitter_login_button'); ?>
                
            </div>
            <?php endif; ?>
            <?php if($this->_linkedinEnabled()): ?>
            <div class="<?php //echo $this->_getButtCol(); ?> tejar-socialconnect-login-lower-linkedin">
                
                    <?php echo $this->getChildHtml('tejar_socialconnect_linkedin_login_button'); ?>
                
            </div>
            <?php endif; ?>            
    </div>
</div>
