<?php
/**
 * Tejar is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="tejar-socialconnect-register">   
	<div class="login_bottom">
					<div class="heading-divider">
					<h5><?php echo $this->__('Or log in with') ?></h5>
					</div>
		</div>
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if($this->_googleEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> tejar-socialconnect-register-google">
            <div class="">
                <?php echo $this->getChildHtml('tejar_socialconnect_checkout_google_button')?>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_facebookEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> tejar-socialconnect-register-facebook">
            <div class="">
                
                <?php echo $this->getChildHtml('tejar_socialconnect_checkout_facebook_button')?>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_twitterEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> tejar-socialconnect-register-twitter">
            <div class="">
                
                <?php echo $this->getChildHtml('tejar_socialconnect_checkout_twitter_button')?>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_linkedinEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> tejar-socialconnect-register-linkedin">
            <div class="">
                
                
                <?php echo $this->getChildHtml('tejar_socialconnect_checkout_linkedin_button')?>
            </div>
        </div>
        <?php endif; ?>        
    </div>
</div>