<?php 
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */

?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
    $_intensoHelper = $this->helper('itactica_intenso');
	$_compare_collection = Mage::helper('catalog/product_compare')->getItemCollection();
	//$_wishlist_collection = Mage::helper('wishlist')->getItemCollection();
	$_wishlist_collection = Mage::helper('wishlist')->getWishlistItemCollection();
    $compareProductsId = '';
	$wishlistProductsId = '';
	// 3SD CODE AJAX CATALOG ADD TO CART
	$store = Mage::app()->getStore();
    $code  = $store->getCode();
	// 3SD CODE AJAX CATALOG ADD TO CART
	/*---------------------------------------- ZEE CODE ----------------------------------*/		
	//--- Initialize Product Id Array to be used while rendring product in collection to avoid product duplication
	 $sliderProductIds = array();
	/*---------------------------------------- ZEE CODE ----------------------------------*/	
?>
<?php if(!$_productCollection->getSize()): ?>

<?php else: ?>
	<div class="container">
		<div class="owl-middle-outer-narrow">
			<?php if($this->_getTitle()): ?><h4 class="owl-title"><span class="content"><?php echo $this->_getTitle(); ?></span></h4><?php endif; ?>
			<div id="featured_related_product" class="owl-top-narrow">
				<div class="filter-products">
					<div class="products owl-carousel" >
						<?php foreach ($_productCollection as $_product): ?>
						<?php /*---------------------------------------- ZEE CODE ----------------------------------*/	
							$product = Mage::getModel('catalog/product')->load($_product->getData('product_id'));  
							if($sliderProductIds && in_array($_product->getId(), $sliderProductIds))continue;
							//--- Pupulate the Slider Products's ids Array
							array_push($sliderProductIds, $_product->getId());
							 
								//--- Get Custom Stock Status if Avialable............
								$customStockStatusText = "";
								$customInStockStatus = true;
								$customStockProduct = Mage::getModel('catalog/product')->load($_product->getId());
								if($customStockProduct->getCustomStockAvailability()){
									$customStockStatusText = Mage::helper('catalog/data')->getCustomStockStatusText($customStockProduct);
									if(Mage::helper('catalog/data')->customStockAddtoCartStatus($_product)){
										$customInStockStatus = true;
									}else{
										$customInStockStatus = false;
									}
									
								}
								/* CONTINUE -  Check if Custom In Stock Status is FALSE and if 'Display Out of Stock Products' Option 
								 * in Admin/Config Catalog Inventory is set to 'YES' Or 'NO'
								 */
								$displayOutOfStockConfigValue = Mage::getStoreConfig('cataloginventory/options/show_out_of_stock');
								if(!$customInStockStatus && !$displayOutOfStockConfigValue)continue;
							/*---------------------------------------- ZEE CODE ----------------------------------*/				
						?>
						<div class="item">
							<div class="item-content">
								<div class="item-images<?php if ($_intensoHelper->isFlushed()): ?> flush<?php endif; ?>">
									<?php $width = 430; ?>
									<?php $_height = Mage::getStoreConfig('intenso/catalog/catalog_product_height', Mage::app()->getStore()); ?>
									<?php $height = $_intensoHelper->getImageHeight($_product, $width, $_height); ?>
									<a class="product-image" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo Mage::helper('itactica_intenso')->getPictureStyle() ; ?>>
									   <?php if (Mage::getStoreConfig('intenso/catalog/lazy_loading') && $_intensoHelper->isKeepAspectRatio() == false): ?>
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" class="item-image" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" src="<?php echo $this->getSkinUrl('images/clear.png'); ?>" data-echo="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>">
											
										<?php else: ?>
											<img id="product-collection-image-<?php echo $_product->getId(); ?>" class="item-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>">
											
										<?php endif; ?>
										<?php echo $_intensoHelper->getAlternativeImgUrl($_product, $width, $height); ?>
									</a>
									 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore())): ?>
											<a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
											
											<?php endif; ?>
										<?php endif; ?>
									<div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel" data-source="category"></div>
									<?php /* if (Mage::helper('itactica_quickview')->isEnabled()): ?>
									<a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
									<?php endif; */ ?>
									<?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())) : ?>
									<a id="wish-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist-custom icons-heart-empty"></a>
									<?php endif; ?>
								</div>
								<div class="item-info">
									<h6 class="item-title">
									<?php if(Mage::getStoreConfig('intenso/catalog/product_name_length', Mage::app()->getStore()) == 4): ?>
									  
										<?php // $_productName = substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, ); 
										$_productName = strlen(trim($_helper->productAttribute($_product, $_product->getName(), 'name')))>=45 ?substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0,40)."...":$_helper->productAttribute($_product, $_product->getName(), 'name');
										?>
										<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span><?php echo $_productName ?></span></a>
									<?php else : ?>
									
									<?php 
										$_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
									?>
										<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="truncate"><span><?php echo $_productName ?></span></a>
									
									<?php endif; ?>
									</h6>
									<?php if($_product->getAttributeText('manufacturer')):?>
										 <p class="brand-list">By:  <span class="by"><?php echo $_product->getAttributeText('manufacturer')?> </span></p>
									 <?php endif;?>
									  <?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
										<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>
									<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', Mage::app()->getStore())): ?>
										<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
											<?php echo $this->getPriceHtml($_product, true) ?>
										<?php endif; ?>
									<?php endif; ?>
										<?php 
										$product = Mage::getModel('catalog/product')->load($_product->getProductId());
										if ($_product->getStockItem()->getIsInStock() && $customInStockStatus): ?>
											<p class="availability in-stock"><span class="hide">Availability:</span>
												<span class="singal-truncate">
													<?php echo $customStockStatusText!=""?$customStockStatusText:"In Stock"?>
												</span>
											</p>
										<?php else :?>
											<p class="availability out-of-stock"><span class="hide">Availability:</span>
												<span class="singal-truncate">
													<?php echo  $customStockStatusText!=""?$customStockStatusText:"Out of Stock"?>
												</span>
											</p>	
										<?php endif; ?>
									
								   
									
									<?php
										// Provides extra blocks on which to hang some features for products in the list
										// Features providing UI elements targeting this block will display directly below the product price
										if ($this->getChild('name.after')) {
											$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
											foreach ($_nameAfterChildren as $_nameAfterChildName) {
												$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
												$_nameAfterChild->setProduct($_product);
												echo $_nameAfterChild->toHtml();
											}
										}
									?>
									<?php if (Mage::helper('itactica_quickview')->isEnabled()): ?>
									<a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
									<?php endif; ?>
									 <?php
									if (Mage::helper('itactica_intenso')->isConfigSwatchesEnabled()) {
										echo $this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/list/swatches.phtml')->setProduct($_product)->toHtml();
									}
									?>
								</div>
							
								<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())): ?>
								<div class="actions clearfix">
								<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', Mage::app()->getStore())): ?>
										<?php // echo $this->getPriceHtml($_product, true) ?>
									<?php endif; ?>
									<?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
										<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>
									<?php if(!$_product->canConfigure() && $_product->isSaleable() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore())): ?>
										 <button type="button" 
										 class="button btn-cart" 
										 title="<?php echo $this->__('Add to Cart') ?>"
										 <?php $code = Mage::app()->getStore();?>
										 <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>
										 onclick="setLocationAjax(this,'<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId(); ?>')"
										 <?php else : ?>
										  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
										 <?php endif; ?>><span><?php echo $this->__('Add to Cart') ?></span></button>
										
										<?php // elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
										<?php else: ?>
										<button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart preview" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
										<?php /*else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php */ ?>
									<?php endif; ?>
									 <?php /* if (Mage::helper('itactica_quickview')->isEnabled()): ?>
										<a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
									<?php endif; */ ?>
									<?php /*  ?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())) : ?>
											<li><a id="wishlist-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore())): ?>
											<li><a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
											</li>
											<?php endif; ?>
										<?php endif; ?>
									</ul>
									<?php */  ?>
								</div>
								<?php endif; ?>
							</div>
						</div>
					<?php endforeach; ?>
					<?php
						//--- Get Homepage Slider Ids Array form Session
						$sliderProductIdArray = Mage::getSingleton('core/session')->getSliderIdArray();
						
						//--- Check if sliderProductIdArray is already populated or not, if Yes then merge Product Id Arrays
						if(!isset($sliderProductIdArray)){ 
							Mage::getSingleton('core/session')->setSliderIdArray($sliderProductIds); 
						}else{
							Mage::getSingleton('core/session')->setSliderIdArray(array_merge($sliderProductIds,$sliderProductIdArray)); 
						}?>
					</div>
				</div>
			</div>
		</div>
	</div>


	<?php
    if (Mage::helper('itactica_intenso')->isConfigSwatchesEnabled()) {
        echo $this->getLayout()->createBlock('configurableswatches/catalog_media_js_list')->setTemplate('configurableswatches/catalog/media/js.phtml')->setProductCollection($_productCollection)->toHtml();
    }
    ?>

    <?php if ($this->getRequest()->isAjax() && Mage::helper('itactica_quickview')->isEnabled()): ?>
    <script>
        new ProductInfo('.quickview-button', '.product-image', {});
        $j(document).trigger('product-media-loaded');
    </script>
    <?php endif; ?>

<?php endif; ?>

<?php  if ($_compare_collection->getSize()): ?>
    <?php foreach($_compare_collection as $product): ?>
           <?php $compareProductsId .= $product->getId() . ','; ?>
    <?php endforeach; ?>
    <?php $compareProductsId = rtrim($compareProductsId, ','); ?>
<script type="text/javascript">
    var compareProducts = Array(0,<?php echo $compareProductsId; ?>);
    for (i = 0; i < compareProducts.length; i++) {
        if ($('compare-id-'+compareProducts[i]) != undefined) $('compare-id-'+compareProducts[i]).addClassName('compared');
    }
</script>
<?php endif; ?>
<?php if ($_wishlist_collection->getSize()): ?>
    <?php foreach($_wishlist_collection as $product): ?>
           <?php $wishlistProductsId .= $product->getProductId() . ','; ?>
    <?php endforeach; ?>
    <?php $wishlistProductsId = rtrim($wishlistProductsId, ','); ?>
	
<script type="text/javascript">
    var wishlistProducts = Array(0,<?php echo $wishlistProductsId; ?>);
    for (i = 0; i < wishlistProducts.length; i++) {
        if ($('wishlist-id-'+wishlistProducts[i]) != undefined)
			$('wishlist-id-'+wishlistProducts[i]).addClassName('active');

			
    }
	
	var wishlistThumbProducts = Array(0,<?php echo $wishlistProductsId; ?>);
    for (i = 0; i < wishlistThumbProducts.length; i++) {
        if ($('wish-id-'+wishlistThumbProducts[i]) != undefined)
			$('wish-id-'+wishlistThumbProducts[i]).addClassName('active');

			
    }
	
</script>

<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}


?>

