<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */

?>
<?php
    $_productCollection = $this->getProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
    $_intensoHelper = $this->helper('itactica_intenso');
	$store = Mage::app()->getStore();
	$showHideAddToCart = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', $store);
	$showHideAddToCartList = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', $store);
	$sliderProductIds = array();
	$isAjax = Mage::getStoreConfig('filterproducts/general_config/ajaxslider' , Mage::app()->getStore());
	$_isNewLabel = Mage::getStoreConfig('intenso/product_label/new_label', Mage::app()->getStore());
	$_isSaleLabel = Mage::getStoreConfig('intenso/product_label/sale_label', Mage::app()->getStore());

?>
<?php if(!$_productCollection->getSize()): ?>
<?php else: ?>
  <?php $collectionLabel = $this->getLabels(); ?>
<div class="filter-products">
<?php echo $this->getPagerHtml() ?>
 <div class="products-slider owl-carousel">
    <?php foreach ($_productCollection->getItems() as $_product): ?>
	<?php
		/*--------------------------------------------------- 3SD CODE ------------------------------------------*/
		$product = $this->getCustomProduct($_product);
		array_push($sliderProductIds, $_product->getId());
		$productUrl = $this->getCustomProductUrl();
		/*--------------------------------------------------- 3SD CODE ------------------------------------------*/
		//--- Get Custom Stock Status if Avialable............
		$customStock = $this->getCustomInStockStatus();
		$customStockStatusText = $customStock['stockStatusText'];
		$customInStockStatus = $customStock['inStockStatus'];
		/*---------------------------------------------------- 3SD CODE -------------------------------------------*/
		/* CONTINUE -  Check if Custom In Stock Status is FALSE and if 'Display Out of Stock Products' Option
			 * in Admin/Config Catalog Inventory is set to 'YES' Or 'NO'
			 */
			$displayOutOfStockConfigValue = Mage::getStoreConfig('cataloginventory/options/show_out_of_stock');
			if(!$customInStockStatus && !$displayOutOfStockConfigValue)continue;
		/*---------------------------------------- ZEE CODE ----------------------------------*/

	?>

        <div class="owl-item item">
            <div class="item-content">
                <div class="item-images<?php if ($_intensoHelper->isFlushed()): ?> flush<?php endif; ?>">
                    <?php $width = 250; ?>
                    <?php $_height = Mage::getStoreConfig('intenso/catalog/catalog_product_height', Mage::app()->getStore()); ?>
                    <?php $height = $_intensoHelper->getImageHeight($_product, $width, $_height); ?>
					<?php $_width = 250; $_height = 202; ?>
					<?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())) : ?>
					<a id="wish-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist-custom icons-heart-empty"></a>
					<?php endif; ?>
                    <a class="product-image" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo Mage::helper('itactica_intenso')->getPictureStyle() ; ?>>
                       <?php if ($isLazyLoading = Mage::getStoreConfig('filterproducts/general_config/lazyload' , Mage::app()->getStore())): ?>
                            <img
							id="product-collection-image-<?php echo $_product->getId(); ?>"
							class="item-image"
							alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
							src="<?php echo $this->getSkinUrl('images/clear.png'); ?>"
              data-lazy="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width); ?>"
              <?php /* ?>
							data-sizes="50vw"
							data-srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width); ?> 1200w,
							<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width); ?> 1400w"
              <?php */ ?>
							width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                        <?php else: ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
							class="item-image"
							alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
              src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width); ?>"
              <?php /* ?>
							sizes="50vw"
							srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_width); ?> 1200w,
							<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width); ?> 1400w"
              <?php */ ?>
							width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                        <?php endif; ?>
						<?php echo $_intensoHelper->getSliderAlternativeImgUrl($_product, $width, null , $isLazyLoading); ?>
                    </a>
					 <?php if($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore())): ?>
                            <a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $store)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>

                            <?php endif; ?>
                        <?php endif; ?>
                    <div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel" data-source="category"></div>
                    <?php $_isNewAvailable = true; ?>
					<?php 
									$values = array();
									$price = $_product->getPrice();
									$specialPrice = $_product->getSpecialPrice();
									$values['PRICE'] = round($price, 2);
									$values['SPECIAL_PRICE'] = round($specialPrice, 2);
									$values['SAVE_AMOUNT'] = round($price - $specialPrice, 2);
									if ($price > 0) {
										$savePercent = round($price - $specialPrice,2) / $price * 100;
										$values['SAVE_PERCENT'] = round($savePercent, 0);
									} else {
										$values['SAVE_PERCENT'] = 0;
									}
									$values['SKU'] = $_product->getSku();
									$values['BR'] = '<br>';
								?>
            					<?php if($_isNewLabel): ?>
            						<?php
            							$now = date("Y-m-d");
            							$newsFrom= substr($_product->getData('news_from_date'),0,10);
            							$newsTo=  substr($_product->getData('news_to_date'),0,10);
            						?>
            						<?php	if ($newsTo != '' || $newsFrom != ''): ?>
            							<?php	if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)): ?>
            								<?php $_isNewAvailable = false; ?>
											<?php 
												$text = $collectionLabel['New'];
												foreach($values as $key => $value) {
													if (!is_array($value)) {
														$text = preg_replace('/{' . $key . '}/', $value, $text); 
													}
												}
											?>
            								<?php  if(isset($collectionLabel['New'])) echo $text; ?>
            							<?php endif; ?>
            						<?php endif; ?>
            					<?php endif; ?>
            					<?php if($_isSaleLabel && $_isNewAvailable && ($_product->getStockItem()->getIsInStock() && $customInStockStatus)): ?>
            						<?php
            							$now = date("Y-m-d");
            							$specialPrice = $_product->getSpecialPrice();
            							$newsFromSpecial = substr($_product->getData('special_from_date'),0,10);
            							$newsToSpecial =  substr($_product->getData('special_to_date'),0,10);
            						?>
            						<?php if ($newsToSpecial != '' || $newsFromSpecial != '' || $specialPrice != ''): ?>
            							<?php if (($newsToSpecial != '' && $newsFromSpecial != '' && $now>=$newsFromSpecial && $now<=$newsToSpecial) || ($newsToSpecial == '' && $now >=$newsFromSpecial) || ($newsFromSpecial == '' && $now<=$newsToSpecial)): ?>
											<?php 
										$text = $collectionLabel['Discount'];
										foreach($values as $key => $value) {
											if (!is_array($value)) {
												$text = preg_replace('/{' . $key . '}/', $value, $text); 
											}
										}
										?>
            							<?php  if(isset($collectionLabel['Discount'])) echo $text; ?>
            							<?php endif; ?>
            						<?php endif; ?>
            					<?php endif; ?>
                </div>
                <div class="item-info">

					<h6 class="item-title">
						<?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
						<?php if(Mage::getStoreConfig('intenso/catalog/product_name_length', $store) == 4): ?>
							<a href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><span class="block truncate-name" id="full-name-<?php echo $_product->getId(); ?>"><?php echo $_productName ?></span></a>
						<?php else : ?>
							<a href="<?php echo $productUrl; ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="truncate"><span><?php echo $_productName ?></span></a>
						<?php endif; ?>
					</h6>
					<?php if($_product->getAttributeText('manufacturer')):?>
						 <p class="brand-list">By:  <span class="by"><?php echo $_product->getAttributeText('manufacturer')?> </span></p>
					<?php endif;?>
					<?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
					<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', Mage::app()->getStore())): ?>

					<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
					<?php endif; ?>

                    <?php endif; ?>
					<?php if ($_product->getStockItem()->getIsInStock() && $customInStockStatus): ?>
						<p class="availability in-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo $customStockStatusText!=""?$customStockStatusText:"In Stock"?></span></p>
					<?php else :?>
						<p class="availability out-of-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo  $customStockStatusText!=""?$customStockStatusText:"Out of Stock"?></span></p>
					<?php endif; ?>
                    <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product price
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
                            }
                        }
                    ?>

					 <?php
					if (Mage::helper('itactica_intenso')->isConfigSwatchesEnabled()) {
						echo $this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/slider/swatches.phtml')->setProduct($_product)->toHtml();
					}
					?>
                </div>
            </div>
		</div>
    <?php endforeach; ?>
	<?php if($this->getRequest()->getParam('sp') == 1): ?>
		<?php $limitCollection = $this->getTotalVisibleProducts() - count($_productCollection); ?>
		<?php if($limitCollection >= 0): ?>
			<?php for($x = 1; $x <= $limitCollection; $x++): ?>
				<div class="owl-item item empty"><div class="ph-item"><div class="ph-col-12"><div class="item-images"><div class="ph-picture-wrapper"><div class="ph-picture"></div></div></div><div class="item-info"><div class="ph-row"><div class="ph-col-6 "></div><div class="ph-col-4 "></div><div class="ph-col-2 "></div><div class="ph-col-6 "></div><div class="ph-col-2 "></div><div class="ph-col-2 "></div><div class="ph-col-4"></div><div class="ph-col-8 empty"></div><div class="ph-col-8"></div><div class="ph-col-4 empty"></div><div class="ph-col-4"></div><div class="ph-col-8 empty"></div></div></div></div></div></div>
			<?php endfor; ?>
		<?php endif; ?>
	<?php endif; ?>
	<?php

		//--- Check if sliderProductIdArray is already populated or not, if Yes then merge Product Id Arrays
    if(!isset($_SESSION["productSliderIds"])){
			$_SESSION["productSliderIds"] = $sliderProductIds;
		} else {
			$_SESSION["productSliderIds"] = array_merge($sliderProductIds,$_SESSION["productSliderIds"]);
		}

    ?>
	</div>
	<?php
    if (Mage::helper('itactica_intenso')->isConfigSwatchesEnabled()) {
        echo $this->getLayout()->createBlock('configurableswatches/catalog_media_js_list')->setTemplate('configurableswatches/catalog/media/slider/js.phtml')->setProductCollection($_productCollection)->toHtml();
    }
    ?>
</div>

<script type="text/javascript">
	<?php if($this->getCompareId()): ?>
		var compareProducts = Array(0,<?php echo $this->getCompareId(); ?>);for (i = 0; i < compareProducts.length; i++) {if ($('compare-id-'+compareProducts[i]) != undefined) $('compare-id-'+compareProducts[i]).addClassName('compared');}
	<?php endif; ?>
	<?php if($this->getWhishlistId()): ?>
		var wishlistProducts = Array(0,<?php  echo $this->getWhishlistId(); ?>);for (i = 0; i < wishlistProducts.length; i++) {if ($('wishlist-id-'+wishlistProducts[i]) != undefined)$('wishlist-id-'+wishlistProducts[i]).addClassName('active');}
		var wishlistThumbProducts = Array(0,<?php  echo $this->getWhishlistId(); ?>);for (i = 0; i < wishlistThumbProducts.length; i++) {if ($('wish-id-'+wishlistThumbProducts[i]) != undefined)$('wish-id-'+wishlistThumbProducts[i]).addClassName('active');}
	<?php endif; ?>
	if(document.readyState === "complete" || document.readyState === "interactive"){
		$j(document).trigger('product-media-loaded');
		altLazyLoad("img.alt-lazyload");
		lazyLoad();
		Intenso.libs.productLabel.init(); // init product labels
	}
</script>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>

<?php endif; ?>
