<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<div style="display: none;" class="tab-content" id="tab_tags_tabbed_contents">
    

    <div class="col-sm-6">
        <?php echo $this->getChildHtml('list_before')?>
        <?php if( $this->getCount() ): ?>
        <p class="small"><?php echo $this->__('Other people marked this product with these tags:') ?></p>
        <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags">
            <?php echo $this->renderTags('<li><a href="%1$s">%2$s <span>(%3$s)</span></a></li>') ?>
        </ul>
        <script type="text/javascript">
            decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
        </script>
        <?php endif; ?>
        <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
            <div class="form-add">
			<p class="small"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
				<div class="input-field">
					<div class="input-box">
						<input type="text" class="input-text required-entry" placeholder="<?php echo $this->__('Add your tags') ?>" name="productTagName" id="productTagName" />
					</div>
					</div>
					<button type="button" title="<?php echo $this->__('Add Tags') ?>" class="btn" onclick="submitTagForm()">
						<span>
							<span><?php echo $this->__('Add Tags') ?></span>
						</span>
					</button>
				
            </div>
            
        </form>
    </div>
<script type="text/javascript">
    //<![CDATA[
	var addTagFormJs;
	document.addEventListener("DOMContentLoaded", function(){
        addTagFormJs = new VarienForm('addTagForm');
	});
	function submitTagForm(){
		if(addTagFormJs.validator.validate()) {
			addTagFormJs.form.submit();
		}
	}
    //]]>
</script>
</div>
