<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product quick view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>

<?php 
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_description = $_product->getDescription();
    $_attributes = new Mage_Catalog_Block_Product_View_Attributes();
    $_attributes->setProduct($_product->getId());
    $_additional = $_attributes->getAdditionalData();
	$_baseUrl = Mage::getBaseUrl();
    $_currentUrl = Mage::helper('core/url')->getCurrentUrl();
	$_relativeUrl = str_replace($_baseUrl, '/', $_currentUrl);
    $_reviews = false;
	$code = Mage::app()->getStore();
?>
<script src="<?php echo $this->getSkinUrl('js/form.mini.js');?>" type="text/javascript"></script>

<script>
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<!-- Product Pic & Info -->


<input type="hidden" id="base_url" value="<?php echo $_baseUrl; ?>" name="base_url"/>
<div class="col-xs-12 product-essential">
    <div class="row flushrow">
		<ul class="messages" style="display:none;">
				<li class="error-msg"><span id="global-notification"></span></li>
			</ul>
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form_quick"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            
            <!-- Central Column: Product info -->
            <div class="col-xs-4 product-shop">
                <h1 id="product_name" class="name" itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
				<div class="product_brand_model">
					<?php if($_product->getAttributeText('manufacturer')!=""){
							
							$brandUrl=Mage::getUrl(); 
							//echo "<h5>",$brandUrl,"</h5>";
							$brandName = strtolower($_product->getAttributeText('manufacturer'));
							$brandName = str_replace(' ', '-', $brandName);
							//--- Fix for replacing space and '&' from brand name.
							$brandName = str_replace(' ', '-', $brandName);
							$brandName = str_replace('-&-', '-', $brandName);
										
					?>
					<p>By: <a href="<?php echo $brandUrl;?><?php echo strtolower($brandName);?>"> <span id="by" itemprop="brand"><?php echo $_product->getAttributeText('manufacturer');?></span></a></p>
					<?php } ?>
					<?php if($_product->getTypeId() != "configurable"){ ?>
						  <?php if($_product->getData('model')): ?><p>Model: <span class="model" itemprop="model"> <?php echo $_product->getData('model');?> </span> </p><?php endif; ?>
					<?php } elseif($_product->getTypeId() == "configurable"){ ?>

						<p id="productModel" style="display:none">Model: <span id="model" class="model" itemprop="model"> <?php //echo $_product->getData('model');?> </span> </p>
					<?php }elseif($_product->getData('sku')!=""){?>
					  <p >Sku: <span id="model" class="model" itemprop="sku" > <?php echo $_product->getData('sku');?> </span> </p>
					<?php } ?>
				</div>
                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php echo $this->getChildHtml('alert_urls') ?>
				<?php echo $this->getChildHtml('media') ?>
                <?php // echo $this->getChildHtml('media_mobile') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getTierPriceHtml() ?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>

                <?php if ($_product->getShortDescription()):?>
                    <div id="short_description" class="short-description">
                        <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                    </div>
                <?php endif;?>
                <?php echo $this->getChildHtml('other');?>
            </div>
            <!-- Right column: Buy Box -->
            <div class="col-xs-4 product-shop-side">
                <?php // if ($_product->isSaleable()):?>
                    <?php echo $this->getChildChildHtml('product_buy_box', '', true, true) ?>
                <?php // endif;?>
                <?php if ($this->canEmailToFriend()): ?>
                    <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
            </div>
        </form>
	 </div>
</div>
<script>
jQuery('.social-wrapper').hide();
</script>
<?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct')): ?>		
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form_quick');
        productAddToCartForm.submit = function(button, url) {
			
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                if (!url) {
                    url = jQuery('#product_addtocart_form_quick').attr('action');
                }
                if(url.indexOf("wishlist/index/cart") != -1){
                    url = url.replace("wishlist/index/cart","ajaxcart/index/add"); // New Code
                } else {
                    url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                }
                url = url.replace("http://", "//");
                url = url.replace("https://", "//");
                var data = jQuery('#product_addtocart_form_quick').serialize();
                data += '&isAjax=1';
                var is_quickview = false;
                if(jQuery("body").hasClass("quickview-index-view")){
                    is_quickview = true;
                }
                if(is_quickview){
                }else{
                    
					jQuery( "#product-addtocart-button-quick" ).prop( "disabled", true );
					jQuery('#quickview-modal .messages').css('display','none');
				}
				try {
                    jQuery.ajax({
                        url : url,
                        dataType : 'json',
                        type : 'post',
                        data : data,
                        success : function(data) {
                            if(is_quickview){
                                
                            }else{
                                jQuery('#loading-mask').hide();
							}
							if(data.status == 'ERROR'){
                                if(is_quickview){
                                    window.parent.alert(data.message.replace("<br/>",""));
                                }
								else{
									jQuery('#quickview-modal .messages').css('display','block');
									jQuery('#quickview-modal #global-notification').html(data.message.replace("<br/>",""));
									}	jQuery( "#quickview-modal #product-addtocart-button-quick" ).prop( "disabled", false );
                            }else{
                                if(is_quickview){
									if(jQuery('.m-hide .cart_sidebar')){
										   jQuery('.m-hide .cart_sidebar').replaceWith(data.cart_sidebar);
											//Apply paging on miniCart throught Intenso JS
										  // Intenso.libs.miniCart.init();
										   jQuery(".sidebar-content").css("height", jQuery(window).height() - 159);
									 }

                                    if(window.parent.jQuery('.m-hide .mini-cart')){
                                        window.parent.jQuery('.m-hide .mini-cart').replaceWith(data.toplink);
                                    }
                                    if(window.parent.jQuery('.fixed-header .mini-cart')){
                                        window.parent.jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                    }
									if(window.parent.jQuery('.sticky-header .mini-cart')){
										window.parent.jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
									}
                                    if(window.parent.jQuery('.col-right .block.block-cart')){
                                        window.parent.jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                    }
                                    window.parent.jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                    <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                    ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                    timer_sec = ajaxcart_sec;
                                    window.parent.jQuery('#after-loading-success-message').fadeIn(200);
                                    ajaxcart_timer = setInterval(function(){
                                        timer_sec --;
                                        window.parent.jQuery('#after-loading-success-message .timer').html(timer_sec);
                                    },1000)
                                    setTimeout(function(){
                                        window.parent.jQuery('#after-loading-success-message').fadeOut(200);
                                        clearTimeout(ajaxcart_timer);
                                        setTimeout(function(){
                                            window.parent.jQuery('#after-loading-success-message .timer').html(ajaxcart_sec);
                                        }, 1000);
                                    },ajaxcart_sec*1000);
                                }
                                else {
									if(jQuery('.m-hide .cart_sidebar')){
										   jQuery('.m-hide .cart_sidebar').replaceWith(data.cart_sidebar);
											//Apply paging on miniCart throught Intenso JS
										  // Intenso.libs.miniCart.init();
										   jQuery(".sidebar-content").css("height", jQuery(window).height() - 159);
									 }
										 
                                    if(jQuery('.m-hide .mini-cart')){
                                        jQuery('.m-hide .mini-cart').replaceWith(data.toplink);
                                    //Apply paging on miniCart throught Intenso JS
											Intenso.libs.miniCart.init();
									}
                                    if(jQuery('.fixed-header .mini-cart')){
                                        jQuery('.fixed-header .mini-cart').replaceWith(data.toplink);
                                    }
									if(jQuery('.sticky-header .mini-cart')){
										jQuery('.sticky-header .mini-cart').replaceWith(data.toplink);
									}
                                    if(jQuery('.col-right .block.block-cart')){
                                        jQuery('.col-right .block.block-cart').replaceWith(data.cart_sidebar);
                                    }
									jQuery('#quickview-modal').foundation('reveal', 'close');
									var myHTML = jQuery('.cart-qty').html();
									jQuery('#cart-qty').html(myHTML);
									
									jQuery( "#product-addtocart-button" ).prop( "disabled", false );
                                    jQuery('#after-loading-success-message #success-message-container .msg-box').html(data.message);
                                    <?php $autoclose = Mage::getStoreConfig('ajaxcart/addtocart/autoclose', $code);?>
                                    ajaxcart_sec = <?php echo ($autoclose && is_numeric($autoclose))?$autoclose:5; ?>;
                                    timer_sec = ajaxcart_sec;
                                    jQuery('.dropdown.cart-dropdown').fadeIn(200);
									jQuery( '#cart-slide-down' ).slideDown( "slow" );
									jQuery( ".product-shop" ).mouseleave(function( event ) {
										jQuery('.dropdown.cart-dropdown').fadeOut(200);
									});
				
                                    ajaxcart_timer = setInterval(function(){
                                        timer_sec --;
                                        
                                    },100);
									
										setTimeout(function(){
										jQuery('.dropdown.cart-dropdown').fadeOut(200);
                                        jQuery('#cart-slide-down').slideUp( "slow" );
                                        clearTimeout(ajaxcart_timer);
                                        setTimeout(function(){
                                          
                                        }, 100);
                                    },ajaxcart_sec*800);

										jQuery( '#continue-btn' ).click(function() {
											jQuery( '#cart-slide-down' ).slideUp( "slow" );  
										});			
									}
								}
								//--- To follow the Admin Check 'After Adding a Product Redirect to Shopping Cart'
								if(data.redirectUrl){
									window.location = data.redirectUrl;
								}
							}
						});
					} catch (e) {
                }                
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }
            }
        }.bind(productAddToCartForm);
		
</script>
<?php else : ?>
<script type="text/javascript">
//<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form_quick');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
        //]]>
</script>
<?php endif; ?>
<script type="text/javascript">
	//--- Short description hide/show length...
		jQuery(document).ready(function() {  
			// EXAMPLE USAGE ON 3 LISTS
			jQuery('#short_description ul').hideMaxListItems({ 'max':4, 'speed':500, 'moreText':'Show more ([COUNT])' });
		
		});
</script>
<?php if(Mage::getStoreConfig('intenso/product_page/swatch_display', Mage::app()->getStore())):?>
<script>		
		//============================ 3SD CODE ==============================//
	
	
			//--- Swatch Dynamic Number of Display and Show More and Less Button...
		jQuery('.product-shop .configurable-swatch-list').each(function () {
			var $thisList = jQuery(this);
			var totalListItems = $thisList.children("li").length;
			var listWidth = $thisList.children("li").width() + 2;
			var listItems = jQuery(this).children("li:gt(<?php echo Mage::getStoreConfig('intenso/product_page/swatch_display', Mage::app()->getStore()) - 1 ; ?>)");
			var listHideItems = jQuery(this).children("li:gt(<?php echo Mage::getStoreConfig('intenso/product_page/swatch_display', Mage::app()->getStore()) - 1 ; ?>)");
			if(jQuery(this).children().length > <?php echo Mage::getStoreConfig('intenso/product_page/swatch_display', Mage::app()->getStore()); ?>){
			listHideItems.hide();
			jQuery(this).append("<li class='more_thum_style' style='min-width:"+listWidth+"px;'><a href='javascript:void(0)' ><span class='more_thum swatch-label' > More <span class='count_number'>("+listItems.length+")</span></span></a></li>");
			jQuery(this).on('click','.more_thum', function(){
				if(jQuery($thisList).children().length >= 17){
					var swatchHeight = <?php echo Mage::getStoreConfig('intenso/product_page/swatch_size', Mage::app()->getStore()); ?>;
					var swatchHeightFun = swatchHeight + swatchHeight + 20;
					jQuery($thisList).css("height",swatchHeightFun);
					jQuery($thisList).css("overflow","auto");
					
				}
				/*
				// one by one li hide and show loop
				var i = 0; 
				(function() { jQuery(listHideItems[i++] || []).fadeToggle(speedPerLI,arguments.callee); })();*/
				listHideItems.toggle();
				jQuery($thisList).toggleClass("active");
				jQuery(this).toggleClass("active");
				if(jQuery($thisList).hasClass("active")){
					jQuery(this).text("Less");
				}
				else{
					jQuery(this).text("More ("+listItems.length+")");
					jQuery($thisList).css("height","auto");
					jQuery($thisList).css("overflow","auto");
				}
			
			});
			}
		});
		
</script>
<?php endif;?>	

<script>		
		  // reinitialize orbit slider and trigger material design form fields (if enabled)
            $j(function() {
                setTimeout(function(){
                    $j(document).foundation();
                    $j(document).trigger('new:ajaxform');
                    // add active class to first bullet
                    var first_bullet = $j('.mobile-gallery .orbit-bullets').children('[data-orbit-slide]').eq(0);
                    first_bullet.addClass('active');
                    lightboxInstance.updateTargets($j('.lightbox'));
                    lightboxMobileInstance.updateTargets($j('.lightbox-mobile'));

                    imagesLoaded($j('.lightbox-mobile > img'), function() {
                        $j(document).resize();
                    });
                    // init additional images slider
                    // Intenso.libs.featured.init();
					var slick = $j(".product-image__slider");
					slick.slick({lazyLoad:"ondemand",dots: true,slidesToShow:1,slidesToScroll:1,speed: 300,appendArrows:!1,adaptiveHeight: true});
		
                    // init product labels
                    Intenso.libs.productLabel.init();
                },500);
            });
</script>
   