<?php
/**
 * Intenso Premium Theme
 * 
 * @category    Itactica
 * @package     Itactica_Intenso
 * @copyright   Copyright (c) 2014-2015 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php 
$_menu = $this->getHtml('level-top');
$_linksArray = @unserialize(Mage::getStoreConfig('intenso/header/main_menu_links', Mage::app()->getStore()));
?>
<?php $helper = Mage::helper('itactica_intenso'); ?>
<nav id="mob_nav" class="top-bar right-off-canvas-menu expanded main-nav <?php echo Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()); ?>" data-topbar>
    <ul class="title-area">
        
        <li class="toggle-topbar menu-icon"><a href="#"><?php echo $this->__('Menu'); ?></a></li>
    </ul>
    <section class="top-bar-section clearfix"> 
        <!-- Right Nav Section -->
        <ul class="right show-for-large-up">
            <li class="has-dropdown show-for-small-only">
            	<a href="<?php echo $this->getUrl('customer/account'); ?>"><span class="sup truncate"><?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?><?php echo $this->__('Hello, %s', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()); ?><?php else: ?><?php echo $this->__('Hello. Sign in'); ?><?php endif; ?></span><?php echo $this->__('Your Account'); ?></a>
                <ul class="dropdown account-dropdown">
                    <li class="arrow-box">
                      	<div class="bg-box">
                      		<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                      		<a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="button sign-in"><?php echo $this->__('Log Out'); ?></a>
                          	<?php else: ?>
                          	<a href="<?php echo $this->getUrl('customer/account'); ?>" class="button sign-in"><?php echo $this->__('Sign in'); ?></a>
                          	<p class="small"><?php echo $this->__('New customer?'); ?> <a href="<?php echo $this->getUrl('customer/account/create'); ?>" ><?php echo $this->__('Start here'); ?></a>.</p>
                          	<?php endif; ?>
                        </div>
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </li>
                </ul>
            </li>
            <li class="has-dropdown show-for-small-only"> 
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span aria-hidden="true" class="icon-cart"></span><span class="sup"><?php echo trim($this->getChildHtml('cart_summary')); ?> <?php echo $this->__('items'); ?></span><?php echo $this->__('Cart'); ?></a>
                <ul class="dropdown cart-dropdown">
                    <li class="arrow-box">
					<div class="mini-cart">
                        <?php echo $this->getChildHtml('minicart_head'); ?>
						</div>
                    </li>
                </ul>
            </li>
        </ul>
		
		<!-- Left Nav Section -->
		
							
							
							
		<ul class="left">

			<?php if (Mage::getStoreConfig('intenso/header/show_home_link', Mage::app()->getStore()) ||
                Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
				<li class="last<?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?> show-for-small-only<?php endif; ?>">
					<a href="<?php echo $this->getUrl('') ?>"><i class="sprite sprite-shop"></i><?php echo $this->__('Home'); ?></a>
				</li>
				
			<?php endif; ?>
			<?php if ($this->getChildHtml('currency_selector') && $helper->mobileCurrencySelector()): ?>
					<?php echo $this->getChildHtml('currency_selector') ?>
				<?php endif; ?>
      <?php if (Mage::getStoreConfig('intenso/header/main_menu_style', Mage::app()->getStore()) == 'vertical'): ?>
        <li class="last has-dropdown vertical-menu-link">
          <a href="<?php echo $this->getUrl('') ?>">
            <span class="show-for-large-only sup"><?php echo $this->__('Shop by'); ?></span>
            <span class="vmenu-title"><?php echo $this->__('Category'); ?></span>
          </a>
        </li>
      <?php endif; ?>
			<?php if (Mage::getStoreConfig('intenso/header/show_categories', Mage::app()->getStore())): ?>
				<li class="group-title"><?php echo $this->__('Shop'); ?></li>
				<li id="megamenu"></li>
				<?php if(Mage::getStoreConfig('intenso/header/header_topmenu_ajax',Mage::app()->getStore()) == 0): ?>
					<?php $_menu = $this->getHtml('level-top'); ?>
					<?php if ($_menu): ?>
						<?php echo $_menu ?>
					<?php endif ?>
				<?php endif ?>
			<?php endif ?>
			<?php if ($_linksArray): ?>
				<?php foreach ($_linksArray as $menuItem): ?>
					<li class="custom-menu<?php if ($menuItem['static_block']): ?> has-dropdown-for-large<?php endif; ?> <?php if ($this->getUrl($menuItem['url']) == $this->getUrl($menuItem['url'])):?>Active<?php endif;?>">
						<a href="<?php echo rtrim($this->getUrl($menuItem['url']), '/'); ?>" ><?php echo $menuItem['menu_item']; ?></a>
						<h2 class="hide"><?php echo $menuItem['menu_item']; ?></h2>
						<?php if ($menuItem['static_block']): ?>
							<div class="dropdown arrow-box">
								<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($menuItem['static_block'])->toHtml(); ?>
							</div>
						<?php endif; ?>
					</li>
				<?php endforeach; ?>
			<?php endif; ?>
			<li class="show-for-small-only group-title"><?php echo $this->__('Pages'); ?></li>
			<li class=""><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Cart'); ?></a></li>
			<li class=""><a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo $this->__('Your Account'); ?></a></li>
			<li class=""><a href="<?php echo $this->getUrl('wishlist'); ?>"><?php echo $this->__('Your Wish List'); ?></a></li>
		</ul>
	</section>
</nav>
<?php if (Mage::getStoreConfig('intenso/header/header_topmenu_ajax', Mage::app()->getStore())): ?>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(){
	var body = document.getElementsByTagName("BODY")[0];
	var url = "/tejar_ajax/index/topMenu/";
	if(body.className.match(new RegExp('(\\s|^)'+'catalog-category-view'+'(\\s|$)'))){
		 url = document.location.href;
	}
	new Ajax.Request(url  + (url.match(new RegExp('\\?')) ? '&isAjax=true' : '?isAjax=true' ) ,{
		method:'get',
		onSuccess: function(transport)    {
			if(200 == transport.status) {
				var json = transport.responseText.evalJSON(true);
				if(body.className.match(new RegExp('(\\s|^)'+'catalog-category-view'+'(\\s|$)'))){
					$("megamenu").update(json.topMenu);	
				} else {
					$("megamenu").update(json);	
				}
				Intenso.libs.ui.init();
				$j(document).foundation();
			}
		},
		onFailure: function(transport){
			$j("#ajax-errors").show();
		}
	});
});
</script>
<?php endif; ?>

 

		