<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<div class="account-forgotpassword">
	<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>    
		<h1 class="account-title center"><?php echo $this->__('Retrieve password') ?></h1>
			<ul class="form-list">
				<li class="row">
					<div class="col-xs-12">
					<div class="input-field input-wrapper">
						<label for="email_address" class="required label-floating"><?php echo $this->__('Email Address') ?></label>
						<input type="email" placeholder="<?php echo $this->__('Email Address') ?>" name="email" id="email_address" class="input-text required-entry validate-email input-floating" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />	
					</div>
					</div>
				</li>
				<?php echo $this->getChildHtml('form.additional.info'); ?>
			</ul>
			<footer class="bottom_box on_the_sides">
				<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="btn btn-big"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<p class="back-link"><a class="arrow-left" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a></p>
			</footer>
		
	</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
