<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="account-create">
    <?php echo $this->getChildHtml('form_fields_before')?>
    
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <h1 class="account-title center"><?php echo $this->__('Create you new account ') ?></h1>
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                <div class="row">
                    <ul class="form-list">
                        <li class="col-sm-12">
                            <div class="row"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?></div>
                        </li>
                        <li class="col-sm-12">
							<div class="input-field input-wrapper">
								<label for="email_address" class="required label-floating"><?php echo $this->__('Email Address') ?></label>
								<input type="email" placeholder="<?php echo $this->__('Email Address') ?>" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text input-floating validate-email required-entry" />
							</div>							
                        </li>
                        <?php if ($this->isNewsletterEnabled()): ?>
                        <li class="col-sm-12">
							<div class="input-box">
								<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="filled-in" checked="checked" />
								<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
							</div>
                        </li>
                        <?php endif ?>
						<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
						<?php if ($_dob->isEnabled()): ?>
							<li class="col-sm-12">
								
									<?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
								
							</li>
						<?php endif ?>
						<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
						<?php if ($_taxvat->isEnabled()): ?>
							<li class="col-sm-6">
								<div class="input-field input-wrapper">
									<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
								</div>
							</li>
						<?php endif ?>
						<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
						<?php if ($_gender->isEnabled()): ?>
							<li class="col-sm-6"><div class="input-field input-wrapper chosen-wrapper select-wrapper"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></div></li>
						<?php endif ?>
						</ul>
						</div>
                <?php if($this->getShowAddressFields()): ?>
                    <input type="hidden" name="create_address" value="1" />
                    <h5 class="legend"><?php echo $this->__('Address Information') ?></h5>
					<div class="row">
                    <ul class="form-list">
                        <li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="company" class="label-floating"><?php echo $this->__('Company') ?></label>
								<div class="input-box">
									<input type="text" name="company" id="company" placeholder="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">                            
							<div class="input-field input-wrapper">
								<label for="telephone" class="required label-floating"><?php echo $this->__('Telephone') ?></label>
								<div class="input-box">
									<input type="tel" name="telephone" placeholder="<?php echo $this->__('Telephone') ?>" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
								</div>
							</div>
                        </li>
						<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="col-sm-12">
							<div class="input-field input-wrapper">
							   <label for="street_1" class="required label-floating"><?php echo $this->__('Address') ?></label>
								<div class="input-box">
									<input type="text" name="street[]" placeholder="<?php echo $this->__('Address') ?>" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text input-floating <?php echo $_streetValidationClass ?>" />
								</div>
							</div>
                        </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="col-sm-12">
							<div class="input-field input-wrapper">
								<label for="street_<?php echo $_i ?>"  class="<?php echo $_streetValidationClass ?> label-floating required"><?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?></label>
								 <div class="input-box">
									<input type="text" name="street[]" placeholder="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text input-floating <?php echo $_streetValidationClass ?>" />
								</div>
							</div>
                        </li>
                    <?php endfor; ?>
                        <li class="col-sm-6">
							<div class="input-field input-wrapper">
								  <label for="city" class="required label-floating"><?php echo $this->__('City') ?></label>
								<div class="input-box">
									<input type="text" placeholder="<?php echo $this->__('City') ?>" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text input-floating <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">
							<div class="input-field  select-wrapper input-wrapper chosen-wrapper">
								<label for="country" class="required chosen-label"><?php echo $this->__('Country') ?></label>
								<?php echo $this->getCountryHtmlSelect() ?>
							</div>
                        </li>
                        <li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="zip" class="required label-floating"><?php echo $this->__('Zip/Postal Code') ?></label>
								<div class="input-box">
									<input type="number" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text input-floating validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
								</div>
							</div>
						</li>
						<li class="col-sm-6">
                                <div class="state-province-field input-field select-wrapper input-wrapper chosen-wrapper">
									<label for="region_id" class="required chosen-label"><?php echo $this->__('State/Province') ?></label>
                                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                    //]]>
                                    </script>
                                    <input type="text" id="region" name="region" placeholder="<?php echo $this->__('State/Province') ?>" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text input-floating validate <?php //echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                </div>
                        </li>
						
                    </ul>
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
					</div>
                <?php endif; ?> 
					<div class="row">
                    <ul class="form-list">
                        <li class="col-sm-6">
                                <div class="input-field input-wrapper">
									<label for="password"  class="required label-floating"><?php echo $this->__('Password') ?></label>
									<div class="input-box">
										<input type="password"  name="password" placeholder="<?php echo $this->__('Password') ?>" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" class="input-text input-floating required-entry validate-password" />
									</div>
								</div>
							</li>
						 <li class="col-sm-6">
							<div class="input-field input-wrapper">
								<label for="confirmation" class="required label-floating"><?php echo $this->__('Confirm Password') ?></label>
								<div class="input-box">
									<input type="password"  name="confirmation" placeholder="<?php echo $this->__('Confirm Password') ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text input-floating required-entry validate-cpassword" />
								</div>
							</div>
                        </li>
						<li class="col-sm-12">
							<?php echo $this->getChildHtml('form.additional.info'); ?>
						</li>
						<li class="col-sm-12">
							<ul>
								<?php echo $this->getChildHtml('persistent.remember.me'); ?>
							</ul>						
						</li>
                    </ul>
					</div>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
				<footer class="bottom_box on_the_sides">
					<button type="submit" onclick="SubmitAndTrimValues('form-validate');" title="<?php echo $this->__('Submit') ?>" class="btn btn-big"><span><span><?php echo $this->__('Submit') ?></span></span></button>
					<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="arrow-left"><?php echo $this->__('Back') ?></a></p>
				</footer>
				<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                        <input name="context" type="hidden" value="checkout" />
                    <?php endif; ?>
    </form>
	
    <script>
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        var regionUpdater = new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        <?php if($this->getShowAddressFields() && Mage::helper('itactica_intenso')->formFieldsType() == 'mdformfields'): ?>
        jQuery(function() {
            jQuery('#country').on('change keyup', function(event) {
                regionUpdater.update();
            });

            if (canUseChosen()) {
                // fix RegionUpdater for chosen.js
                Object.extend(Validation, {
                    isVisible : function(elm) {
                        while(elm.tagName != 'BODY') {
                            // validate DOB and Region hidden select boxes
                            if (elm.id == 'month' || elm.id == 'day' || elm.id == 'year' || elm.id == 'region_id') {
                                return true;
                            }
                            if(!$(elm).visible()) return false;
                            elm = elm.parentNode;
                        }
                        return true;
                    }    
                });
                regionUpdater.update = regionUpdater.update.wrap(function(parentMethod){
                    // parent "update" method call
                    parentMethod();
                     
                    // after "update" method fires
                    regionUpdater.regionSelectEl.hide();
                    regionChosen = jQuery('#region_id_chosen');
                    if(regionUpdater.regionTextEl.visible()) {
                        regionChosen.hide();
                        regionChosen.parent().removeClass('input-box-select');
                        regionChosen.parent().parent().removeClass('select-list');
						jQuery('.state-province-field  label').removeClass('chosen-label');
						jQuery('.state-province-field  label').addClass('label-floating');
                    } else {
                        regionChosen.show();
                        regionChosen.parent().addClass('input-box-select');
                        regionChosen.parent().parent().addClass('select-list');
                        jQuery('#region_id').trigger("chosen:updated");
						jQuery('.state-province-field  label').removeClass('label-floating');
						jQuery('.state-province-field  label').addClass('chosen-label');
                    }
                });

                jQuery('#region_id').on('change keyup', function(event) {
                    jQuery('#region').val(jQuery(this).children("option").filter(":selected").text());
                });
                regionUpdater.update();

            } else {
                regionUpdater.update = regionUpdater.update.wrap(function(parentMethod){
                    // parent "update" method call
                    parentMethod();
                     
                    // after "update" method fires
                    if(regionUpdater.regionTextEl.visible()) {
                        jQuery('.state-province-field').removeClass('select-list');
                        jQuery('.state-province-field > .input-box').removeClass('input-box-select');
						jQuery('.state-province-field  label').removeClass('chosen-label');
						jQuery('.state-province-field  label').addClass('label-floating');
                    } else {
                        jQuery('.state-province-field').addClass('select-list');
                        jQuery('.state-province-field > .input-box').addClass('input-box-select');
						jQuery('.state-province-field  label').removeClass('label-floating');
						jQuery('.state-province-field  label').addClass('chosen-label');
                    }
                });
                regionUpdater.update();
            }

            function canUseChosen() {
                if (window.navigator.appName === "Microsoft Internet Explorer") {
                    return document.documentMode >= 8;
                }
                if (/iP(od|hone)/i.test(window.navigator.userAgent)) {
                    return false;
                }
                if (/Android/i.test(window.navigator.userAgent)) {
                    if (/Mobile/i.test(window.navigator.userAgent)) {
                        return false;
                    }
                }
                return true;
            }
        });
        <?php endif; ?>
	
		//==================================================== ZEE CODE ============================================//
		/*
		*@name   SubmitAndTrimValues
		*@params formID
		*@return none (trims whitespaces from form values)
		*/
		function SubmitAndTrimValues(formIdToSubmit){
			
			jQuery('#'+formIdToSubmit+' *').filter(':input').each(function(){
				if(jQuery(this).attr('id')=="firstname" || jQuery(this).attr('id')=="lastname" || jQuery(this).attr('id')=="email"){
					this.value=jQuery(this).val().trim();
				}
			});
			jQuery('#'+formIdToSubmit).submit();
		}
		//===================================================== ZEE CODE ============================================//
		
    </script>
</div>
