<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<div class="account-forgotpassword">
	<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	<h1 class="center account-title"><?php echo $this->__('Reset a Password') ?></h1>
	<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
		
			<ul class="form-list">
				<li class="row">
						<div class="col-xs-12">
							<div class="input-field input-wrapper">
								<label for="password" class="required label-floating"><?php echo $this->__('New Password'); ?></label>
								<input type="password" placeholder="<?php echo $this->__('New Password'); ?>" class="input-text required-entry validate-password input-floating " name="password" id="password" />
							</div>
						</div>
					</li>
					<li class="row">
						<div class="col-xs-12">
							<div class="input-field input-wrapper">
								<label for="confirmation" class="required label-floating"><?php echo $this->__('Confirm New Password'); ?></label>
								<input type="password" placeholder="<?php echo $this->__('Confirm New Password'); ?>" class="input-text required-entry validate-cpassword input-floating " name="confirmation" id="confirmation" />
						</div>
					</div>
				</li>
			</ul>
			<footer class="bottom_box on_the_sides">
				<button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="btn btn-big"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
			</footer>
	</form>
</div>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
