<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category  = Mage::getModel('catalog/layer')->getCurrentCategory();
    $_intensoHelper = $this->helper('itactica_intenso');
	$_compare_collection = Mage::helper('catalog/product_compare')->getItemCollection();
	//$_wishlist_collection = Mage::helper('wishlist')->getItemCollection();
	$_wishlist_collection = Mage::helper('wishlist')->getWishlistItemCollection();
    $compareProductsId = '';
	$wishlistProductsId = '';
	// 3SD CODE AJAX CATALOG ADD TO CART
	$store = Mage::app()->getStore();
    $code  = $store->getCode();
	// 3SD CODE AJAX CATALOG ADD TO CART
	  $_productNameIdArray = array();
	  
	$showHideAddToCart = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore());
	$showHideAddToCartList = Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', Mage::app()->getStore());
?>

<?php if(!$_productCollection->getSize()): ?>
    <?php $emptyCollectionBlock = $this->getLayout()->createBlock('cms/block')->setBlockId('category_empty_collection')->toHtml(); ?>
	<div class="catalog-list-empty">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<h1 id="category-name" class="empty-catalog"><?php echo $_category->getName(); ?></h1>
            <?php if ($emptyCollectionBlock): ?>
                <?php echo $emptyCollectionBlock; ?>
            <?php else: ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
            <?php endif; ?>
				</div>
			</div>
		</div>
			<?php if ($emptyCollectionBlock): ?>
			<?php else: ?>
				<?php echo $this->getChildHtml('left.reports.product.viewed') ?>
			<?php endif; ?>
        </div>
    
    <?php if (!$this->getRequest()->isAjax() && Mage::helper('core')->isModuleOutputEnabled('Itactica_FeaturedProducts')): ?>
        <?php if (Mage::getStoreConfig('intenso/catalog/empty_category_featured')): ?>
            <?php echo $this->getLayout()->createBlock('itactica_featuredproducts/view')->setIdentifier(Mage::getStoreConfig('intenso/catalog/empty_category_featured'))->setTemplate('itactica_featuredproducts/view.phtml')->toHtml() ?>
        <?php endif; ?>
    <?php endif; ?>
<?php else: ?>
<?php if (!$this->getRequest()->isAjax()): ?>
<div class="tejar-catalog">
<section class="products-grid clearfix" data-list-qty="<?php echo (int) Mage::getStoreConfig('itactica_layerednavigation/catalog/list_items_qty'); ?>">
	<div class="container">
    <div id="ajax-errors" style="display: none;">
        <ul class="ajax-message">
            <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
        </ul>
    </div>
    <?php echo $this->getToolbarHtml(); ?>
    <?php if($_description=$_category->getDescription()): ?>
        <div class="row category-description">
            <div class="col-sm-12">
                <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
            </div>
        </div>
	
    <?php endif; ?>
	</div>
    <?php echo $this->getChildHtml('catalog.leftnav'); ?>
    <?php echo $this->getChildHtml('catalogsearch.leftnav'); ?>
	<div class="category-container">
    <ul id="catalog-listing" class="category-products<?php if ($_intensoHelper->isKeepAspectRatio()): ?> keep-aspect-ratio<?php endif; ?><?php if ($this->helper('itactica_layerednavigation')->isAjaxEnabled()): ?> ajax<?php endif; ?><?php if ($_intensoHelper->isInfiniteScroll()): ?> infinite-scroll<?php endif; ?> clearfix <?php if($this->getMode()!='grid'): ?>list<?php endif; ?>">
<?php endif; ?>
    <?php foreach ($_productCollection as $_product): ?>
	<?php 
	/*---------------------------------------- ZEE CODE ----------------------------------*/	
	//--- Get Custom Stock Status if Avialable............
			$customStockStatusText = "";
			$customInStockStatus = true;
			$customStockProduct = Mage::getModel('catalog/product')->load($_product->getId());
			if($customStockProduct->getCustomStockAvailability()){
				$customStockStatusText = Mage::helper('catalog/data')->getCustomStockStatusText($customStockProduct);
				if(Mage::helper('catalog/data')->customStockAddtoCartStatus($_product)){
					$customInStockStatus = true;
				}else{
					$customInStockStatus = false;
				}
				
			}
			/* CONTINUE -  Check if Custom In Stock Status is FALSE and if 'Display Out of Stock Products' Option 
			 * in Admin/Config Catalog Inventory is set to 'YES' Or 'NO'
			 */
			$displayOutOfStockConfigValue = Mage::getStoreConfig('cataloginventory/options/show_out_of_stock');
			if(!$customInStockStatus && !$displayOutOfStockConfigValue)continue;
			/*---------------------------------------- ZEE CODE ----------------------------------*/	
	?>
        <li class="item isotope-item">
            <div class="item-content clearfix">
                <div class="item-images<?php if ($_intensoHelper->isFlushed()): ?> flush<?php endif; ?>">
                    <?php $width = 430; ?>
                    <?php $_height = Mage::getStoreConfig('intenso/catalog/catalog_product_height', Mage::app()->getStore()); ?>
                    <?php $height = $_intensoHelper->getImageHeight($_product, $width, $_height); ?>
                    <a class="product-image" href="<?php echo Mage::getUrl().$_product->getUrlKey(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" <?php echo Mage::helper('itactica_intenso')->getPictureStyle() ; ?>>
                        <?php if (Mage::getStoreConfig('intenso/catalog/lazy_loading') && $_intensoHelper->isKeepAspectRatio() == false): ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" class="item-image" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" src="<?php echo $this->getSkinUrl('images/clear.png'); ?>" data-echo="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                            <?php echo $_intensoHelper->getAlternativeImgUrl($_product, $width, $height, true); ?>
                        <?php else: ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" class="item-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width,$height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $width; ?>" height="<?php echo $height; ?>">
                            <?php echo $_intensoHelper->getAlternativeImgUrl($_product, $width, $height); ?>
                        <?php endif; ?>
                    </a>
					 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore())): ?>
								<a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    <div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel" data-source="category"></div>
                    <?php /* if (Mage::helper('itactica_quickview')->isEnabled()): ?>
                    <a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
                    <?php endif; */ ?>
					<?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())) : ?>
					<a id="wish-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist-custom icons-heart-empty"></a>
					<?php endif; ?>
                </div>
                <div class="item-info">
					<?php if(Mage::getStoreConfig('intenso/catalog/product_name_length', Mage::app()->getStore()) == 4): ?>
					<?php  $_productName        = trim($_product->getName()); 
						   $_productId         = $_product->getId();
						  // $_productNameIdArray[$_productId]=str_replace('"','\"',$_productName);
						   $_productNameIdArray[$_productId]=$_productName;
					?>
					<h6 class="item-title <?php if(strlen($_productName) >=40 ): ?> truncating <?php endif; ?>">
					 <a  href="<?php echo Mage::getUrl().$_product->getUrlKey(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
						<span class="hide"><?php echo $this->stripTags($_product->getName(), null, true) ?></span>
						<span class="product-name-span-<?php echo $_productId?>"><!-- Product Names,On Mobile Devices are To be Filled Dynamically based on the Screen Width --></span></a>
                    </h6>
					<?php else : ?>
					<h6 class="item-title">
					<?php 
						$_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
					?>
                        <a href="<?php echo Mage::getUrl().$_product->getUrlKey(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="truncate"><span><?php echo $_productName ?></span></a>
                    </h6>
					<?php endif; ?>
					 <h6 class="item-title list-title">
                        <a href="<?php echo Mage::getUrl().$_product->getUrlKey(); ?>" class="" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
							<span class="<?php echo $_productId?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
						</a>
                    </h6>
					<?php if($_product->getAttributeText('manufacturer')):?>
						 <p class="brand-list">By:  <span class="by"><?php echo $_product->getAttributeText('manufacturer')?> </span></p>
					 <?php endif;?>
					  <?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
					<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', Mage::app()->getStore())): ?>
						<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>
					<?php endif; ?>
					 	<?php 
						$product = Mage::getModel('catalog/product')->load($_product->getProductId());
						if ($_product->getStockItem()->getIsInStock() && $customInStockStatus): ?>
							<p class="availability in-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo $customStockStatusText!=""?$customStockStatusText:"In Stock"?></span></p>
						<?php else :?>
							<p class="availability out-of-stock"><span class="hide">Availability:</span><span class="singal-truncate"><?php echo $customStockStatusText!=""?$customStockStatusText:"Out of Stock"?></span></p>	
						<?php endif; ?>
                    <div class="item-description">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                   

                    <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product price
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                    ?>
                    <?php if (Mage::helper('itactica_quickview')->isEnabled() &&
					!Mage::helper('itactica_quickview')->isDisabledForMobile()): ?>
                    <a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
                    <?php endif; ?>
                </div>
				
				 <?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
                <div class="actions clearfix <?php if($showHideAddToCart):?>grid-block<?php endif; ?> <?php if($showHideAddToCartList):?>list-block<?php endif; ?>">
				<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_price_tag', Mage::app()->getStore())): ?>
					<?php if($_product->isSaleable() &&  $customInStockStatus == true ): ?>
                        <?php echo $this->getLayout()->createBlock('catalog/product_price')->setTemplate('catalog/product/custom_clone_price.phtml')->setProduct($_product)->setDisplayMinimalPrice(true)->toHtml(); ?>
						<?php // echo $this->getLayout()->createBlock('catalog/product_price')->setTemplate('catalog/product/custom_clone_price.phtml')->setProduct($_product)->setDisplayMinimalPrice(true)->setIdSuffix($idSuffix='amit')->toHtml(); ?>
                    <?php endif; ?>
				<?php endif; ?>
                    <?php if($_product->getRatingSummary() && Mage::getStoreConfig('intenso/catalog/catalog_show_products_rating', Mage::app()->getStore())): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
				
					<?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart', Mage::app()->getStore()) || Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_cart_list', Mage::app()->getStore())): ?>  
					<?php if(!$_product->canConfigure() && $_product->isSaleable() &&  $customInStockStatus == true ): ?>
                         <button type="button" 
						 class="button btn-cart" 
						 title="<?php echo $this->__('Add to Cart') ?>"
						 <?php $code = Mage::app()->getStore();?>
						 <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>
						 onclick="setLocationAjax(this,'<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId(); ?>')"
						<?php else : ?>
						  onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
						 <?php endif; ?>><span><?php echo $this->__('Add to Cart') ?></span></button>
						
						<?php // elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
						<?php else: ?>
                        <button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart preview" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
						<?php /*else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php */ ?>
                    <?php endif; ?>
					<?php endif; ?>
					 <?php /* if (Mage::helper('itactica_quickview')->isEnabled()): ?>
                        <a href="<?php echo $this->getUrl('itactica_quickview/product/view/id/' . $_product->getId()) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="quickview-button button"><?php echo $this->__('Quick View') ?></a>
                    <?php endif; */ ?>
					<?php /*  ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow() && Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_wishlist', Mage::app()->getStore())) : ?>
                            <li><a id="wishlist-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxWishlist(this,'<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');"<?php endif;?>  title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <?php if(Mage::getStoreConfig('intenso/catalog/catalog_show_add_to_compare', Mage::app()->getStore())): ?>
                            <li><a id="compare-id-<?php echo $_product->getId(); ?>" href="<?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>javascript:void(0)<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)):?>onclick="ajaxCompare(this,'<?php echo $_compareUrl ?>','<?php echo $_product->getId()?>');"<?php endif; ?> class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
							</li>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
					<?php */  ?>
                </div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    <?php if ($this->getRequest()->isAjax() && Mage::helper('itactica_quickview')->isEnabled()): ?>
    <script>
        new ProductInfo('.quickview-button', '.product-image', {});
        $j(document).trigger('product-media-loaded');
    </script>
    <?php endif; ?>
<?php if (!$this->getRequest()->isAjax()): ?>
    </ul>
	</div>
	<div id="pager" class="toolbar-bottom">
    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/pager.phtml')->toHtml(); ?>
</div>
</section>
</div>
<?php endif; ?>
<?php endif; ?>

<?php  if ($_compare_collection->getSize()): ?>
    <?php foreach($_compare_collection as $product): ?>
           <?php $compareProductsId .= $product->getId() . ','; ?>
    <?php endforeach; ?>
    <?php $compareProductsId = rtrim($compareProductsId, ','); ?>
<script type="text/javascript">
    var compareProducts = Array(0,<?php echo $compareProductsId; ?>);
    for (i = 0; i < compareProducts.length; i++) {
        if ($('compare-id-'+compareProducts[i]) != undefined) $('compare-id-'+compareProducts[i]).addClassName('compared');
    }
</script>
<?php endif; ?>
<?php if ($_wishlist_collection->getSize()): ?>
    <?php foreach($_wishlist_collection as $product): ?>
           <?php $wishlistProductsId .= $product->getProductId() . ','; ?>
    <?php endforeach; ?>
    <?php $wishlistProductsId = rtrim($wishlistProductsId, ','); ?>
	
<script type="text/javascript">

    var wishlistProducts = Array(0,<?php echo $wishlistProductsId; ?>);
    for (i = 0; i < wishlistProducts.length; i++) {
        if ($('wishlist-id-'+wishlistProducts[i]) != undefined)
			$('wishlist-id-'+wishlistProducts[i]).addClassName('active');
    }
	
	var wishlistThumbProducts = Array(0,<?php echo $wishlistProductsId; ?>);
    for (i = 0; i < wishlistThumbProducts.length; i++) {
        if ($('wish-id-'+wishlistThumbProducts[i]) != undefined)
			$('wish-id-'+wishlistThumbProducts[i]).addClassName('active');
		}
	
</script>

<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}

?>
<script>
jQuery(window).on('orientationchange resize', function(e) {
	setproductName(jQuery.parseJSON('<?php echo addslashes(json_encode($_productNameIdArray)); ?>'),'<?php echo $this->getUrl('tejar_catalog/category/ajaxScreenWidth'); ?>');
});
jQuery('catalog-listing').ready(function(){
	//jQuery('#catalog-listing').on(function(e){
		setproductName(jQuery.parseJSON('<?php echo addslashes(json_encode($_productNameIdArray)); ?>'),'<?php echo $this->getUrl('tejar_catalog/category/ajaxScreenWidth'); ?>');
	//});
});
</script>