
<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>

<div class="row">
	<div class="col-sm-3 account-nav-content">
	<div class="page-title">
		<h1><?php echo $this->__('My Account'); ?></h1>
	</div>
<nav class="account-nav-container top-bar left-off-canvas-menu main-nav" role="navigation" data-topbar id="filter_nav">
    <section class="layered-nav top-bar-section">
        <div class="block block-account">
            <div class="block-content">
                <ul class="links-list">
                    <li class="show-for-small-only group-title"><?php echo $this->__('My Account'); ?></li>
                    <?php $_links = $this->getLinks(); ?>
                    <?php $_index = 1; ?>
                    <?php $_count = count($_links); ?>
                    <?php foreach ($_links as $_link): ?>
                        <?php $_last = ($_index++ >= $_count); ?>
                        <?php if ($this->isActive($_link)): ?>
                            <li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><i class="sprite sprite-<?php echo $_link->getName() ?>"></i><?php echo $_link->getLabel() ?></a></li>
                        <?php else: ?>
                            <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><i class="sprite sprite-<?php echo $_link->getName() ?>"></i><?php echo $_link->getLabel() ?></a></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </section>
</nav>
</div>