<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="mobile-account-head">
<button type="button" title="<?php echo $this->__('Add New Address') ?>" class="btn-big btn secondary " onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
</div>
        <ol class="account_address">
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="address-box">
				<div class="box-title">
					<h5><?php echo $this->__('Default Billing Address') ?> </h5>
				</div>
				<div class="box-content">
					<address>
						<?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
					</address>
				</div>
				<div class="box-action">
					<a class="" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" title="<?php echo $this->__('Change Billing Address') ?>"><span><?php echo $this->__('Change Billing Address') ?></span></a>
				</div>				
           </li>
        <?php else: ?>
            <li class="address-box">                
				<div class="box-title">
					<h5><?php echo $this->__('Default Billing Address') ?></h5>
				</div>
				<div class="box-content">
					<p><?php echo $this->__('You have no default billing address in your address book.') ?></p>
				</div>
            </li>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="address-box">
				<div class="box-title">
					<h5><?php echo $this->__('Default Shipping Address') ?> </h5>
				</div>
				<div class="box-content">
					<address>
						<?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
					</address>
				</div>
				<div class="box-action">
					<a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>" title="<?php echo $this->__('Change Shipping Address') ?>"><span><?php echo $this->__('Change Shipping Address') ?></span></a>
				</div>
            </li>
        <?php else: ?>
            <li class="address-box empty">
                <div class="box-title">
					<h5><?php echo $this->__('Default Shipping Address') ?></h5>
				</div>
				<div class="box-content">
					<p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
				</div>
            </li>
        <?php endif ?>
        </ol>
    
	
    
		
	
        <ol class="account_address">
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php $i=1; foreach($_pAddsses as $_address): ?>
            <li class="address-box">
               	<div class="box-title">
					<h5><?php echo $this->__('Additional Address %d', $i) ?></h5>
				</div>
				<div class="box-content">
					<address>
						<?php echo $this->getAddressHtml($_address) ?>
					</address>
				</div>
				<div class="box-action">
					<a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>" title="<?php echo $this->__('Edit Address') ?>"><span><?php echo $this->__('Edit') ?></span></a> 
						  &nbsp; | &nbsp;
					<a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');" title="<?php echo $this->__('Delete Address') ?>"><span><?php echo $this->__('Delete') ?></span></a>
				</div>
            </li>
            <?php $i++; endforeach; ?>
        <?php else: ?>
            <li class="address-box empty">
               <div class="box-title">
					<h5><?php echo $this->__('Additional Address %d', 1) ?></h5>
				</div>
				<div class="box-content">
					<p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
				</div>
            </li>
        <?php endif ?>
        </ol>
    
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	
</div>


<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
