<?php
/**
 * Tejar is not affiliated with or in any way responsible for this code.
 *
 * Commercial support is available directly from the [extension author](http://www.techytalk.info/contact/).
 *
 * @category Marko-M
 * @package SocialConnect
 * @author Marko Martinović <marko@techytalk.info>
 * @copyright Copyright (c) Marko Martinović (http://www.techytalk.info)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="clearer">
    <div class="tejar-socialconnect-linkedin">
        <div class="tejar-socialconnect-linkedin-inner">
          <button data-message="Connecting with Linked in..." 
				onclick="popwin('<?php echo $this->escapeUrl($this->_getButtonUrl());?>')">
                <?php echo $this->_getButtonText(); ?>            
			</button>
        </div>
        <div class="tejar-socialconnect-linkedin-right"></div>
    </div>
</div>