<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */

?>
<!doctype html>
<html lang="en" class="no-js">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass(). Mage::helper('itactica_intenso')->getStoreClass() . ' ' . Mage::helper('itactica_intenso')->formFieldsType() .'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
	<div class="off-canvas-wrap">
		<div class="inner-wrap">
			<?php echo $this->getChildHtml('global_notices') ?>
			<?php echo $this->getChildHtml('header') ?>
			<div class="breadcrumbs-container">
			<div class="container">
			<?php echo $this->getChildHtml('breadcrumbs') ?>
			</div>
			</div>
			<?php echo $this->getChildHtml('global_messages') ?>


			<div class="main-container">

				<div class="container">

					<?php echo $this->getChildHtml('content') ?>

				</div>
			</div>


		</div><!-- /inner-wrap -->
    <?php echo $this->getChildHtml('footer_before') ?>
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getAbsoluteFooter() ?>
    <a class="exit-off-canvas"></a>
	</div><!-- /off-canvas-wrap -->
<?php echo $this->getChildHtml('before_body_end') ?>
<div class="loading-bar"></div>
</body>
</html>
