<div class="mini-cart">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())
    ?>
    <?php $_items = $this->getRecentItems();
			
	?>
	<div class="dropdown-title"><?php echo $this->__('Your Cart (%s)', $_cartQty); ?><a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="icon-edit" title="<?php echo $this->__('Edit your Cart'); ?>"><span class="hide"><?php echo $this->__('Edit Cart'); ?></span></a></div>
	
    <span class="cart-qty" style="display:none;"><?php echo $_cartQty ?></span>
	
                <?php $_items = $this->getRecentItems() ?>
                <?php if(count($_items)): 
				//echo "<pre>"; var_dump($_items);die;?>
				 <div class="mini-products-wrapper">
					<div class="mini-products-container">
                    <ul id="cart-sidebar" class="mini-products-list">
                        <?php $i=0; foreach($_items as $_item): ?>
                        <?php if ($i != 0 && $i % 3 == 0): ?>
                            </ul>
                            <ul id="cart-sidebar" class="mini-products-list">
                        <?php endif; ?>
                        <?php  echo $this->getItemHtml($_item) ?>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                    </ul>
					</div>
					</div>
                  <?php else: ?>
        <p class="small cart-empty"><?php echo $this->__('Your shopping cart is currently empty.') ?></p>
    <?php endif ?>

    <div class="bg-box">
        <p class="subtotal">
            <?php echo $this->__('Subtotal:') ?>&nbsp;
            <?php if ($this->canApplyMsrp()): ?>
                <span class="price" title="<?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>">
                    [?]
                </span>
            <?php else: ?>
                <span class="price">
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?>
                    <?php else: ?>
                        <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php endif; ?>
                </span>
            <?php endif; ?>
        </p>
        <a href="<?php echo $this->getCheckoutUrl() ?>" class="button sign-in"><?php echo $this->__('Checkout') ?></a>
    </div>
    <div class="sb-cart-dropdown">
        <?php echo $this->getChildHtml('cart_promotion') ?>
    </div>
</div>