<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
?>
<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
?>
<li id="remember-me-box-<?php echo Mage::helper('core')->getRandomString(10); ?>" class="control">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box">
        <input type="checkbox" name="persistent_remember_me" class="filled-in" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Remember Me') ?>" />
		<label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
		<a class="link-tip" href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Checking Remember Me will let you access your shopping cart on this device when you are logged out.') ?>"><?php echo $this->__('What\'s this?') ?></a>
		
    </div>

</li>
